### ISSUE TITLE
GH Page | Live Update For Indices

### ISSUE THREAD

**Issue by GoPro16** [algolia/docsearch-configs#1024]
It would be awesome to throw a quick GH page up that just displays a list of the last index times for all the configs. I know that it would help me out in knowing exactly the last time my site was indexed rather than waiting 24 hours and maybe missing that it happened 20 minutes after I had made a change to my site.

If you expose this API publicly behind a API Key I would love to contribute and make something like this. Otherwise, if there is some other way that we can keep track of this that would be great to know

**Comment by s-pace** [comment]
Thanks for opening an issue. Please [open it on the scraper repo](https://github.com/algolia/docsearch-scraper/issues) so that we do not loose track of it.
