### ISSUE TITLE
Broken links to the sesarch results on the local build of vuepress

### ISSUE THREAD

**Issue by Minhsh** [algolia/docsearch-configs#1033]
# Do you want to request a **feature** or report a **bug**?

A bug?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=ibm_z_open_editor

## What is the **current** behaviour?
I requested an apiKey and indexName for our doc site built by Vuepress, and I inserted the code snippet in the config.js and ran a local build with yarn docs:dev. The search results were displayed, but the problem is that when clicked the results, they all returned 404. I want to check if this is the intended behavior (do not work on local build for the first time) before pushing the search to our production doc site?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
I tested this on my local build of vuepress. 

## What is the **expected** behaviour?
When I click the search results, the links should work.

**Comment by s-pace** [comment]
👋 @Minhsh 

Thanks for the details. I can confirm you that the URL stored within Algolia are correctly set up and links are not broken. I have used the regular UI and it works well. Could you check that the URL is not edited by the JS snippet integrated by Vuepress thanks to the `transformData` method?

Please send us an example of the wrong URL.

**Comment by Minhsh** [comment]
@s-pace Thanks for checking! When you clicked the result, did it return 404 or the correct page?

I also got the same search result, and saw the same link (https:ibm.gihub.....) when I hovered over the result. But when I clicked the result, it went to http://localhost:8080/zopeneditor-about/zopeneditor-about/Docs/git_createbranches.html which is broken and returned 404.

Then, I removed the line _base: '/zopeneditor-about/'_ in config.js and ran a local build again. When I clicked the result, it went to http://localhost:8080/zopeneditor-about/Docs/git_createbranches.html which is also broken and returned 404. 

Not sure how to fix this.

**Comment by s-pace** [comment]
> @s-pace Thanks for checking! When you clicked the result, did it return 404 or the correct page?

The correct page with a 200 :)

I think the behavior your are describing is custom to vuepress which edit the domain of the URL to avoid breaking the navigation when DEV environment. It should not impact the website once deployed. 

Assumption confirmed [by this piece of code](https://github.com/vuejs/vuepress/blob/c6f1322f5536d59af65bec5069e155ff0a72916c/packages/%40vuepress/theme-default/components/AlgoliaSearchBox.vue#L47).

Once your website is live and the daily crawl done, everything will be updated and the search experience will not be broken :)
