### ISSUE TITLE
Re-indexing request

### ISSUE THREAD

**Issue by jseldess** [algolia/docsearch-configs#1110]
We've been seeing missing results in our docs search for cockroachlabs.com/docs. Can you please re-index to see if that solve the problem? 

https://github.com/algolia/docsearch-configs/blob/master/configs/cockroachlabs.json

Also, the config references our docs sitemap, which was missing for the last months. It's back as of today, so wondering if that's going to make a difference.

**Comment by s-pace** [comment]
Hi @jseldess 

Crawl triggered and over, if you still still experience some page missing, please list these URLs here.

Thanks
