### ISSUE TITLE
libelektra.org: Search stopped working

### ISSUE THREAD

**Issue by markus2330** [algolia/docsearch-configs#1113]
@s-pace created a [docsearch config](https://github.com/algolia/docsearch-configs/blob/master/configs/elektra.json) for us, which we integrated: https://github.com/ElektraInitiative/libelektra/issues/1815

## What is the **current** behaviour?

Most terms, do not yield any search results. E.g. when typing 'dump' or 'clion' there are no results even though pages which have this in the title exist.

## What is the **expected** behaviour?

That any word that exists in the documentation is also found.

#### Any quick clues?

maybe related to #756

**Comment by s-pace** [comment]
Issue solved by running a crawl. This issue is related to the need of using a headless chrome to correctly render your website. Would it possible to only rely on server side rendering on your end @markus2330 ?

Thanks

**Comment by markus2330** [comment]
Thank you for fixing the issue!

> Would it possible to only rely on server side rendering on your end @markus2330 ?

The problem is that the person who integrated the search is not available anymore and I do not know how to change that.

**Comment by s-pace** [comment]
Thanks for the details.

When I meant only rely on server side rendering, it applies to the whole website. The issue here is how you add the `active` class to the element matching the xpath selector `//ul[contains(@class, 'nav')]//li[contains(@class, 'active')][1]/preceding::span[1]`
