### ISSUE TITLE
brew_all: casks not tagged clearly

### ISSUE THREAD

**Issue by slokhorst** [algolia/docsearch-configs#1127]
On https://formulae.brew.sh/, there are a few items that are searchable, including:

* formulae (https://formulae.brew.sh/formula/), selectors_key `formula`
* casks (https://formulae.brew.sh/cask/), selectors_key `cask`

They both index fine, but they are hard to distinguish, since the casks aren't clearly marked as such:
![algolia-brew-cask](https://user-images.githubusercontent.com/8083666/69334310-bb77c500-0c5a-11ea-9b37-47a97c83f661.png)
(in the screenshot, the first entry, listed under "Formulae", is a formula, and the second entry, listed under "Homebrew Formulae" is a cask)

It would be nice if the casks are listed under "Casks" instead of "Homebrew Formulae".

**Comment by s-pace** [comment]
Sure, it is completely doable. We are currently relying on the h1 header but we can make it happen.

I let @MikeMcQuaid confirm this request since he is the owner of the website. Once I have his ✅, I will update the configuration and run a crawl.

**Comment by MikeMcQuaid** [comment]
> I let @MikeMcQuaid confirm this request since he is the owner of the website. Once I have his ✅, I will update the configuration and run a crawl.

👍 sounds like this would be a notable improvement, thanks both @slokhorst and @s-pace!
