### ISSUE TITLE
brew_all: crawl stuck

### ISSUE THREAD

**Issue by slokhorst** [algolia/docsearch-configs#1175]
There are results missing from the search again. See Homebrew/formulae.brew.sh#175 for more information.

**Comment by s-pace** [comment]
Sorry for that @slokhorst 

I haven't checked it yet but the issue here is most likely the time limit. I have increased this limit. 

Feel free to reopen this thread if needed. We will solved it shortly.

Thanks

**Comment by slokhorst** [comment]
Thanks again @s-pace ! I will let you know if I encounter the problem again in the future.

**Comment by slokhorst** [comment]
@s-pace It's that time again... there are results missing from the search.

**Comment by slokhorst** [comment]
Bump.. still broken.
