### ISSUE TITLE
Reindexing after domain changed

### ISSUE THREAD

**Issue by onevcat** [algolia/docsearch-configs#162]
Hi,

Here is my config file: https://github.com/algolia/docsearch-configs/blob/master/configs/uniwebview.json

I've changed my domain from "unidocs.onevcat.com" to "docs.uniwebview.com" several days ago. However, the navigation destination of search result are still pointing to the old domain.

I guess it is due to the old index in using and the new ones are not valid yet.

I want to confirm is there anything like expiring duration for index? What is the reindex policy and is it possible to request a reindex immediately?

Thanks!

**Comment by ElPicador** [comment]
It should be ok now. 
Your DocSearch was disabled.

**Comment by onevcat** [comment]
Thanks!
