### ISSUE TITLE
The records are 0 when run crawler locally

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#1794]
# Do you want to request a **feature** or report a **bug**?
**bug**
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=pingcap

## What is the **current** behaviour?
I created an algolia dashboard account in free trail, The first two times I ran with the [config](https://github.com/algolia/docsearch-configs/blob/master/configs/pingcap.json) and got about 247k records, which I think is too large. So I removed some levels from selector and recrawel again.  ![image](https://user-images.githubusercontent.com/34967660/76995576-0399c080-698b-11ea-8fe8-e255c95337a0.png)When finished, I got 57k records, however, I cannot search some expected docs. So I added the removed levels back, and ran the forth time, but the Log shows 0 records.
![image](https://user-images.githubusercontent.com/34967660/76996431-78b9c580-698c-11ea-85eb-5ec386285c14.png)

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
I dont know why the crawler does not add records to index when I run my own.

#### What have you tried to solve it?
I am going to upgrade algolia plan, so I am trying to test it run my own. I have granted Algolia to access the my index with APPLICATION_ID = BH4D9OD16A. Would you please take a look? Thanks for you help!

#### Any quick clues?
Does I update the selector content level affect the records?

**Comment by tonyneel923** [comment]
What was the answer to this @YiniXu9506
