### ISSUE TITLE
Versioned doc search not working 

### ISSUE THREAD

**Issue by danielmai** [algolia/docsearch-configs#1857]
# Do you want to request a **feature** or report a **bug**?
bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name="dgraph"`

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Search results always go to the latest version of the docs instead of showing and leading to results for the currently viewed version.

What works: latest version
1. Go to https://dgraph.io/docs
2. In the search box, search for anything (e.g., "General")
    ![image](https://user-images.githubusercontent.com/2251820/79148984-46c53480-7d7b-11ea-8d97-ed0fb28a2547.png)
3. Clicking the first result goes to https://dgraph.io/docs/faq/#general. This is expected.

What doesn't work: 
1. Go to a specific version of the docs: https://dgraph.io/docs/v1.2.2
2. In the search box, search for anything (e.g., "General")
3. Clicking the first result goes to https://dgraph.io/docs/faq/#general. This should go to the page for the version v1.2.2: https://dgraph.io/docs/v1.2.2/faq/#general

#### What have you tried to solve it?
I'm not sure what the fix is, but I suspect there's an issue with the new config.

#### Any quick clues?

I had recently updated dgraph.json in #1848, where the previous config was working for versioned search with the previous domain (docs.dgraph.io).

**Comment by s-pace** [comment]
You only need to hit the merge button from https://github.com/dgraph-io/hugo-docs/pull/46 :)
