### ISSUE TITLE
Update drone_io documentation

### ISSUE THREAD

**Issue by bradrydzewski** [algolia/docsearch-configs#186]
hey all, I was hoping for some help updating the indexing for the [drone_io](https://github.com/algolia/docsearch-configs/blob/master/configs/drone_io.json) documentation. We have moved the documentation:

```diff
{
  "index_name": "drone_io",
  "start_urls": [
-   "http://readme.drone.io/"
+   "http://docs.drone.io/sitemap/"
  ],
```

We have also adjusted the structure. I was hoping that perhaps Algolia could crawl the documentation using the sitemap only (at http://docs.drone.io/sitemap/). This would allow us to make structural changes to the main documentation, without having to re-configure the crawling, since the sitemap structure would never change.

Do you think this would be possible?

I would offer to submit a pull request but was unsure if the below notation was correct, and I was having trouble setting up an environment to test myself (I will keep trying, though)

```diff
-    "lvl0": "header nav a.selected",
-    "lvl1": "main h1",
-    "lvl2": "main h2",
+    "lvl0": "body > ul > li > span",
+    "lvl1": "body > ul > li > ul > li > span",
+    "lvl2": "body > ul > li > ul > li > ul > li > a",
```

**Comment by ElPicador** [comment]
Seems good to me :)
Put everything in a PR and we'll deploy it
