### ISSUE TITLE
Move `*.netlify.com` to `*.netlify.dev`

### ISSUE THREAD

**Issue by kidonng** [algolia/docsearch-configs#1866]
Netlify is using a new domain `netlify.dev` instead of the old `netlify.com` for sites deployed without custom domains. I failed to find a public announcement on their website, but they have sent several emails regarding this change. Here is an excerpt:

> Hello,
>
> A reminder that starting April 14, 2020, sites without a custom domain are being moved from `your-site.netlify.com` to `your-site.netlify.app`. New websites will also have URLs ending with netlify.app, unless you specify a custom domain.
> Why the change? We're investing in the security and stability of our infrastructure, and this step is necessary on that journey.
>
> ...
>
> **Will my current sites continue to work?**
> Absolutely. Any sites already deployed to `your-site.netlify.com` will continue to operate, just as they do now. Traffic to any `your-site.netlify.com` address will be forwarded to `your-site.netlify.app` seamlessly and automatically, using a 301 redirect. (This tells browsers and search engines that the site has moved, so they know the new location.)

I suggest changing DocSearch config using `*.netlify.com` to `*.netlify.dev` which can save redirects and may prevent further problems.

**Comment by s-pace** [comment]
We ask maintainer to submit a PR on their configuration. We do not want to wrongly change these URL. Thanks for warning.
