### ISSUE TITLE
Expo not fully indexed

### ISSUE THREAD

**Issue by byCedric** [algolia/docsearch-configs#1885]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name`?

`index_name="expo"`

## What is the **current** behaviour?

We recently made some changes in the versioning of the [Expo docs](https://docs.expo.io). Right now, only the API references are versioned. All guides and intros are now extracted from that versioning.

Unfortunately, the docs search only covers the versioned pages. It does not return any result from either "Get Started" or "Guides". The Expo configuration does include the pages by `start_url` `https://docs.expo.io`. If I run this locally with the crawler, I'm getting the other pages indexed as well. Is this something we configured wrong, or does it need to be reindexed?

## What is the **expected** behaviour?

Search results returning "Get Started" and/or "Guides".

#### What have you tried to solve it?

Running the crawler locally.

#### Any quick clues?

Maybe we should add a wildcard at `https://docs.expo.io/.*`, or just a reindex 😄 

### Any other feedback / questions ?

It's still an awesome search tool, thanks!

**Comment by s-pace** [comment]
Done, LMK if you need anything

**Comment by byCedric** [comment]
Awesome, thanks! ❤️ Working like a charm!
