### ISSUE TITLE
Puppet (open source version)

### ISSUE THREAD

**Issue by phrawzty** [algolia/docsearch-configs#189]
The base reference manual: https://docs.puppet.com/puppet/latest

Note that Puppet _Server_, Hiera, and PuppetDB are split out into their own components (see https://docs.puppet.com/puppet/).

**Comment by phrawzty** [comment]
Perhaps worth noting that there's also an Enterprise offering that has its own documentation: https://docs.puppet.com/pe/latest/index.html

**Comment by phrawzty** [comment]
Closed via 45f74c156bff5ab65a9f3952a4c5776df54d18e6 🥋

**Comment by ElPicador** [comment]
🍾
