### ISSUE TITLE
Arrow-kt.io results have been reduced

### ISSUE THREAD

**Issue by rachelcarmena** [algolia/docsearch-configs#1898]
# Do you want to request a feature or report a bug? A bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=arrow

## What is the **current** behaviour?

Some pages aren't being found now. For instance https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/-option/index.html when searching by `Option`.

## What is the **expected** behaviour?

Previous page was found before.

#### Any quick clues?

The searchable content and the number of records that are extracted and indexed seem to be explicitly reduced as part of a recent change: https://github.com/algolia/docsearch-configs/commit/44ec7e22dd822afd9477c59a9ab7d75967217080 

Please, could these links be replaced?
```
    "https://arrow-kt.io/docs/0.10/",
    "https://arrow-kt.io/docs/0.10/core/"
```
by:
```
    "https://arrow-kt.io",
```

### Any other feedback / questions ?

Thank you very much.

**Comment by s-pace** [comment]
It does crawl it. Can you double check please?

**Comment by rachelcarmena** [comment]
Thanks for your reply. I've checked it again and I see the same result. Thanks again!

**Comment by s-pace** [comment]
Seems it work:
![image](https://user-images.githubusercontent.com/32097720/80714395-2b855380-8af5-11ea-8b2b-690a285cf48d.png)

**Comment by s-pace** [comment]
Can you provide a sitemap pls?

**Comment by rachelcarmena** [comment]
Thanks @s-pace for your assistance. Of course, please, find it attached: 
[arrow-kt-docs-pages.txt](https://github.com/algolia/docsearch-configs/files/4573739/arrow-kt-docs-pages.txt) 

Please, was it closed by mistake? I'd appreciate the information about this issue. Is there a limit about search results? Why is it necessary to provide the sitemap from our side? Thanks in advance!

**Comment by s-pace** [comment]
We need a sitemap available from your website please. It can be available under <root>/sitemap.xml

This issue is closed since it is not due to the configuration itself

**Comment by rachelcarmena** [comment]
Oh, sorry, I misunderstood the question. So we're going to locate a XML file with the sitemap content on https://arrow-kt.io/sitemap.xml. I'll write a comment here when it's available. Thanks @s-pace

**Comment by rachelcarmena** [comment]
Hi again @s-pace , it's already available in https://arrow-kt.io/sitemap.xml. Please, what would the next steps be?

**Comment by s-pace** [comment]
Should be good now

**Comment by rachelcarmena** [comment]
Thanks @s-pace When looking for `Option`, it shows results by `Optional` and `OptionT` now. Please, how could we change that result with `sitemap.xml`? Would `priority` tag be considered? Thanks in advance!

**Comment by s-pace** [comment]
Do you mean `page_rank`? https://docsearch.algolia.com/docs/config-file/#using-page-rank

**Comment by rachelcarmena** [comment]
Not exactly though I think it's similar: https://www.sitemaps.org/protocol.html#prioritydef

However, could `h1` be missing here: https://github.com/algolia/docsearch-configs/blob/master/configs/arrow.json#L27

Thank you so much, @s-pace !

**Comment by rachelcarmena** [comment]
Hi! I've created #1906 to help with it :+1:
