### ISSUE TITLE
Bootstrap 4.5.0 no results

### ISSUE THREAD

**Issue by XhmikosR** [algolia/docsearch-configs#1951]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= bootstrap

## What is the **current** behaviour?

No results

---

@s-pace we released a new version an hour ago and the docs don't have any results. See https://github.com/twbs/bootstrap/issues/30792

We’d like to find a solution so that indexes are updated immediately, or perhaps on demand somehow, so that we don’t have issues during our releases in the future.

In v4, we use https://github.com/twbs/bootstrap/blob/v4-dev/site/_includes/docs-sidebar.html#L2 and https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.5/assets/js/src/search.js#L28

Thanks in advance!

EDIT: we actually use the same way in master too.

**Comment by s-pace** [comment]
We are working on making the crawl on-demand. Stay tuned.

New release ✅

**Comment by XhmikosR** [comment]
Thanks @s-pace for the fast response!

Will we see an announcement when the change happens? Until then, should I assume we need to make a new issue whenever we release a new minor/major version?

**Comment by s-pace** [comment]
Yes sure we will let you know.

Yes please open an issue or ping me. The crawl will happen within 24h tough. Making a silent release would help too since we crawl the whole website.

**Comment by XhmikosR** [comment]
Hey, @s-pace. It seems our old search broke, see https://github.com/twbs/bootstrap/issues/30820

I checked all versions >= 4.0 and 4.3 and 4.4 both don't return any results.

**Comment by XhmikosR** [comment]
Thanks @s-pace!
