### ISSUE TITLE
Ruby docs

### ISSUE THREAD

**Issue by DirtyF** [algolia/docsearch-configs#197]
Search seems currently broken on https://ruby-doc.org/core/

If only they could add Docsearch to their build pipleline 🙏

**Comment by ElPicador** [comment]
@DirtyF thanks for telling us 😄 
Do you have a contact in the ruby core documentation team?

**Comment by DirtyF** [comment]
👋  @ElPicador : I just know that @hsbt is part of the Ruby core team 💎  and maintain another Ruby docs website (https://docs.ruby-lang.org/en/2.4.0/) whose [repository is on Github](https://github.com/ruby/docs.ruby-lang.org). Both are generated with Rdoc I guess, Docsearch could replace the search in [the current theme](https://github.com/ged/darkfish).

**Comment by ElPicador** [comment]
They would need to do some integration, so we need to have a request coming from them.
Or if you are willing you can prepare the PR on the doc

**Comment by s-pace** [comment]
Feel free to request or to reopen if needed. Looks done
