### ISSUE TITLE
Broken docsearch (NoSuchKey) 

### ISSUE THREAD

**Issue by bartanthonissen** [algolia/docsearch-configs#1975]
# Do you want to request a **feature** or report a **bug**?

a bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= scantrust

## What is the **current** behaviour?

Docusaurus ID's have been updated, (Removed all capital letters out of ID's and directory names)
and the searchbar still points to old paths, resulting in an error: ```NoSuchKey``` 

If I'm not mistaking the crawler should run every 24 hours? Shouldn't this pick up these updates?

## What is the **expected** behaviour?

Document searches point to the new updated paths. 

### Any other feedback / questions ?

Can we do something from our side to fix this. Does this require a rebuild or a new build of the index?

**Comment by s-pace** [comment]
Did you use   apiKey: '664fc82b5c3144d8e4fba3dd3a7063db' & indexName: 'scantrust'  ?
