### ISSUE TITLE
Version Config

### ISSUE THREAD

**Issue by cangencer** [algolia/docsearch-configs#2041]
We're using the default docsearch config for docusaurus 1.x for https://jet-start.sh as can be seen here:

https://github.com/algolia/docsearch-configs/blob/master/configs/hazelcast-jet.json

For some reason, even though version is added as a facet it's not reflected in the search results. When I search for a term, it's showing the same page multiple times, as it appears in different versions. What can be done to help docsearch understand different versions rather than indexing everything as the same or just putting the older versions as stop URLs?

**Comment by s-pace** [comment]
We do facet on these values:
![image](https://user-images.githubusercontent.com/32097720/84390015-415b5d80-abf7-11ea-92bb-477db76a3844.png)

**Comment by cangencer** [comment]
how can I prevent the older versions duplicating in search results?

**Comment by s-pace** [comment]
By merging https://github.com/hazelcast/hazelcast-jet/pull/2322

**Comment by cangencer** [comment]
Thanks @s-pace! Now I notice that actually the blog posts are no longer appearing in search results. Is there a workaround for that?

**Comment by s-pace** [comment]
I think the selectors need an update.
