### ISSUE TITLE
Bootstrap v5.0.0-alpha1

### ISSUE THREAD

**Issue by XhmikosR** [algolia/docsearch-configs#2053]
Hello!

Yesterday we released Bootstrap v5.0.0-alpha1 and we used a subdomain, https://v5.getbootstrap.com/

@s-pace: forgot to ping you sooner, do we need something else on our side? The stable build, when it's released, will use the main domain.

Thanks!

Refs https://github.com/twbs/bootstrap/issues/31060

**Comment by XhmikosR** [comment]
Thanks @s-pace!

Just so that we are safe, when we move the docs back to the main domain, things should work automatically, correct?

**Comment by s-pace** [comment]
Congrats for the new release!

You will need to update the URL of the v5 by submitting a PR.

**Comment by XhmikosR** [comment]
>Congrats for the new release!

Thanks!

But I'm still confused about how this works, because when we move the v5 docs to the main repo/domain, the URL will be `getboostrap.com` and just the `extra_attributes` version will be `5.0`.

I was under the impression that this way we don't need to update anything.

**Comment by s-pace** [comment]
Yes but you will need to make sure `https://v5.getbootstrap.com/` -> `https://getbootstrap.com/docs/5.0/` otherwise the crawler will not go through this part of your documentation

**Comment by XhmikosR** [comment]
When we release v5.0.0 stable or maybe beta, we'll move the docs to the main repo so they will be under `getbootstrap.com`. I'll probably ping you anyway when the time comes :)
