### ISSUE TITLE
docs.growingio.com can not get any search result after 2020-06-24

### ISSUE THREAD

**Issue by hokor** [algolia/docsearch-configs#2074]
# Do you want to request a **feature** or report a **bug**?

**bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=`growingio`

## What is the **current** behaviour?
Our docs site (https://docs.growingio.com) can not get any search result after 2020-06-24
![image](https://user-images.githubusercontent.com/16695773/85937451-3f530780-b936-11ea-8e83-c8be233b5f3f.png)

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

1. Open GrowingIO Docs https://docs.growingio.com/
2. Type a world in the search input box, eg. `growingio`,`API`,`SDK` ...
3. Always show `No result found by query "xxx"`

![image](https://user-images.githubusercontent.com/16695773/85937311-e767d100-b934-11ea-9aa1-13d522b8ca95.png)

## What is the **expected** behaviour?
Display matched search result by key word.

#### What have you tried to solve it?
I don't have any idea for this ☹️.
#### Any quick clues?
It worked well before 2020-06-24.
Here is our [Confing](https://github.com/algolia/docsearch-configs/blob/7a4b1a86c22d304e125f9c7f7e0ebf66f6685c47/configs/growingio.json
)

**Comment by s-pace** [comment]
👋 @hokor,

It seems that the content of the website has changed. The [selectors defined on your configuration are not matching anymore](https://github.com/algolia/docsearch-configs/blob/7a4b1a86c22d304e125f9c7f7e0ebf66f6685c47/configs/growingio.json#L30-L36). Could you add back the static class `docSearch-content` please? The crawler rely on this class to extract content from the documentation.

Let us know once this is live. Thanks

**Comment by hokor** [comment]
The class `docSearch-content` has been added.
Could you please reindex our site again?

Thank you so much!

**Comment by s-pace** [comment]
Sure.

I have triggered a new crawl. It has completed and should solve this issue :)

**Comment by hokor** [comment]
It worked. Thanks! 👍
