### ISSUE TITLE
New formik docs, config updates needed

### ISSUE THREAD

**Issue by jaredpalmer** [algolia/docsearch-configs#2077]
Old site: https://jaredpalmer.com/formik

New site: https://formik.org

**Comment by s-pace** [comment]
Congrats for the release and implementing the v3 🚀 

Once you want to introduce new languages and new versions of your pages, can you introduce these informations as meta tags please? [You can find further details here.](https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags)
