### ISSUE TITLE
https://v2.docusaurus.io/ search not working

### ISSUE THREAD

**Issue by omry** [algolia/docsearch-configs#2120]
![image](https://user-images.githubusercontent.com/376455/88450069-102e9980-ce01-11ea-8617-d3aba1af57ab.png)

**Comment by s-pace** [comment]
Issue solved once the daily crawl happened. The new alpha version created new pages that needed to be indexed too.
![image](https://user-images.githubusercontent.com/32097720/88534533-92d57580-d008-11ea-9f89-9b05abbecd21.png)
