### ISSUE TITLE
Section parents displayed incorrectly [stancl-tenancy]

### ISSUE THREAD

**Issue by stancl** [algolia/docsearch-configs#2122]
# Do you want to request a **feature** or report a **bug**?

Something in between. I'm trying to improve the current behavior, which is not working as one would expect.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= stancl-tenancy

## What is the **current** behaviour?

Categories, instead of pages, are displayed as the "parent" of sections - see https://github.com/algolia/docsearch-configs/pull/2024#issuecomment-641228773

## What is the **expected** behaviour?

Ideally, in the example given above, I'd see "Event system" as the parent of the "TenancyServiceProvider" section.

#### What have you tried to solve it?

Asked here :P

#### Any quick clues?

Either it can be fixed in the index config, or a sitemap change must be made on my end (not sure).

**Comment by s-pace** [comment]
@stancl the update of your configuration should have solved this issue.

![image](https://user-images.githubusercontent.com/32097720/88535466-37a48280-d00a-11ea-8903-25f1a6f0c698.png)

**Comment by stancl** [comment]
Thanks Sylvain!
