### ISSUE TITLE
public "metadata" in the docsearch configs?

### ISSUE THREAD

**Issue by phrawzty** [algolia/docsearch-configs#221]
It would be useful for tracking and reporting purposes to have some fields in the configs that aren't necessarily used by the scraper. Immediately I'd like to add:
* `name`: Canonical, human-readable label (such as company or project name) for a given config.
* `human_url`: A URL that a human could go to and get the documentation site.
I'm not married to those key names - suggestions welcome. 😄

**Comment by maxiloc** [comment]
This is already doable 😄, it's just a matter of adding them.

For name => it's what we try to do with index_name but sometimes it can be quite tricky.

**Comment by phrawzty** [comment]
Following the conversation on Slack, I further propose an object `tags` which can contain whatever human-readable elements that may be interesting. Example:
```json
"tags": {
  "name": "Super PHP Framework 2000",
  "url": "https://human.readab.le/entrypoint#to-the-docs",
  "categories": [
    "framework",
    "php",
    "ecommerce"
  ]
}
```

**Comment by phrawzty** [comment]
Following the conversation on Slack, I further propose an object `tags` which can contain whatever human-readable elements that may be interesting. Example:
```json
{
	"tags": {
		"name": "Super PHP Framework 2000",
		"url": "https://human.readab.le/entrypoint#to-the-docs",
		"categories": [
			"framework",
			"php",
			"ecommerce"
		]
	}
}
```

**Comment by phrawzty** [comment]
Concept validated. Now we figure out how to automate and scale. ;)
