### ISSUE TITLE
bug(pomerium): updated / changed path not being indexed

### ISSUE THREAD

**Issue by desimone** [algolia/docsearch-configs#2308]
# Do you want to request a **feature** or report a **bug**?

Bug, but I am probably holding it wrong :) 

https://github.com/algolia/docsearch-configs/blob/master/configs/pomerium.json

### If it is a DocSearch index issue, what is the related `index_name` ?

  "index_name": "pomerium",

## What is the **current** behaviour?

One of the documentation paths / pages is not being indexed.  

1. Go to https://www.pomerium.com/reference/
2. Search for any heading or item on the reference page (e.g. `spdy`) and no results are returned. 

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?

I expected that location to be indexed similar to the other listed paths like `docs` and `guides`

#### Any quick clues?

Perhaps these URLS have not been whitelisted somewhere?

**Comment by s-pace** [comment]
Thanks for rising.

Issue solved by https://github.com/algolia/docsearch-configs/commit/1117e578c31923a81c569e092927127f65bcb1a6
