### ISSUE TITLE
Parse same website with 2 designs

### ISSUE THREAD

**Issue by pierallard** [algolia/docsearch-configs#244]
Hi Algolia team !

I have a question about this configuration
https://github.com/algolia/docsearch-configs/blob/master/configs/akeneo.json

We will introduce a new design (same as https://api.akeneo.com/ ) for the v2.0 (the old design is still here :  https://docs.akeneo.com/2.0/index.html)

So the parsing configuration between paths https://docs.akeneo.com/1.x/ and https://docs.akeneo.com/2.x/ will not be the same.

My question is: is it possible to have 2 configurations (one for 1.x and one for 2.x) ? If not, don't worry, we will bring back the new design for the previous 1.x paths.

Regars

Pierre
Akeneo

**Comment by s-pace** [comment]
Hi @pierallard,

We may have replied to this issue by DM but I would still like to give you a proper answer to this common use case.

You can have *several independent* and *different ways to indexed* your data. This is introduced by the `selectors_key ` attribute from your `star_urls` sub object. It will define a new selectors and thus change your *scraping strategy*.

If you want to also to *restrict search to a subset of results* (such as records from the same version) you can also [use our facet feature](https://www.algolia.com/doc/guides/searching/faceting/). In DocSearch, This will be made from our snippet by adding the following input: 
`algoliaOptions`: { `facetFilters`: [*"**tagName**:**tagValue**"*] }:

##### A concrete example is worth more than a long speech:

We will define 2 different strategies from the default one. Please keep in mind that `start_urls` are considered as *regular expression* too.
```
  "start_urls": [
    "https://www.algolia.com/doc/guides/"
    {
      "url": "matching URLs",
      "selectors_key": "api_reference",
      "tags": [
        "api_reference"
      ]
    },
    {
      "url": "https://www.algolia.com/doc/tutorials/",
      "selectors_key": "tutorials",
      "tags": [
        "tutorials"
      ]
    }
  ],
  "selectors": {
    "default": {
      "lvl0": ".content-inner h1",
      "lvl1": ".content-inner h2",
      "lvl2": ".content-inner h3",
      "lvl3": ".content-inner h4",
      "lvl4": ".content-inner h5",
      "text": ".content-inner p, .content-inner li"
    },
    "api_reference": {
    [STRATEGY A]  
    },
     "tutorials": {
    [STRATEGY B] 
    }
[...]
}
```

Let me know if you need anything else

**Comment by s-pace** [comment]
I closed it. Feel free to open it and/or giving us any more feedback.

**Comment by pierallard** [comment]
That's perfect guys! Thanks for this complete answer.
