### ISSUE TITLE
[smooch_v2] New config, same API key?

### ISSUE THREAD

**Issue by alexibz** [algolia/docsearch-configs#2455]
If I added a new config would the apiKey be the same? Can I just update the indexName for the new config file name?

**Comment by Shipow** [comment]
yes, you could have both indices under the same App, same ACL and same api Key.

**Comment by alexibz** [comment]
I've updated the [smooch_v2.json](https://github.com/algolia/docsearch-configs/blob/master/configs/smooch_v2.json) yesterday and today I'm getting the following AlgoliaSearchError:
`message: "Index not allowed with this API key"` 

The apiKey is the same as for smooch.json.

**Comment by Shipow** [comment]
Hello, i've updated the ACL accordingly, now it should show up.

**Comment by ktquez** [comment]
@Shipow All right?

I started to configure it in our doc [vue-a11y.json](https://github.com/algolia/docsearch-configs/blob/master/configs/vue-a11y.json) and I'm getting the same message, could you tell me what I need to do to make it work too?

**Comment by Shipow** [comment]
hey @ktquez, you need to use the apiKey that we provided you by email. Send an email to docsearch support if you don't find it.
