### ISSUE TITLE
[gitlab] Algolia doesn't index words inside codeblocks

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch-configs#2529]
# Do you want to request a **feature** or report a **bug**?

Bug.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=`gitlab`

## What is the **current** behaviour?

Text inside codeblocks is not indexed.

- Docs example: https://docs.gitlab.com/ee/integration/omniauth.html#automatically-link-existing-users-to-omniauth-users
- Search for `auto_link_user`: https://docs.gitlab.com/search/?query=auto_link_user

## What is the **expected** behaviour?

Text inside codeblocks should be indexed.

#### What have you tried to solve it?

Nothing yet.

#### Any quick clues?

This should have something to do with our config, probably need to add something at https://github.com/algolia/docsearch-configs/blob/8b205e62c1d6daa0ed03f55b477f8444dd511d16/configs/gitlab.json#L60

For reference, our codeblocks are inside a `code` HTML element , for example:

```html
<pre class="highlight">
<code><span class="na">omniauth</span><span class="pi">:</span>
  <span class="na">auto_link_user</span><span class="pi">:</span> <span class="pi">[</span><span class="s2">"</span><span class="s">saml"</span><span class="pi">,</span> <span class="s2">"</span><span class="s">twitter"</span><span class="pi">]</span>
</code>
</pre>
```

### Any other feedback / questions ?

You rock!

**Comment by shortcuts** [comment]
Hi,

As you pointed it, adding **.article-content pre.highlight code** to your **text** selector will add the code to the index.
You can edit your config and open a PR and I'll merge it ASAP!

Have a nice day

**Comment by axilleas** [comment]
@axilleas great! I opened https://github.com/algolia/docsearch-configs/pull/2553. Thanks a lot!
