### ISSUE TITLE
Rasa index is not working correctly since 2 weeks ago

### ISSUE THREAD

**Issue by m-vdb** [algolia/docsearch-configs#2555]
# Do you want to request a **feature** or report a **bug**?

Hi there, I want to report a **bug** with your crawler. We recently updated our index configuration, now leveraging [tags](https://github.com/algolia/docsearch-configs/blob/ecfdd53fe102b23f2610b851320e19947694e593/configs/rasa.json#L3-L16). We have multiple docs sites powered by Docusaurus (one for each tag) and the search for each of these is currently not working as expected:

- https://rasa.com/docs/rasa (tags=[rasa]): the search yields results for both Rasa and Rasa X
- https://rasa.com/docs/rasa-x (tags=[rasa-x]): the search never returns results
- https://rasa.com/docs/action-server (tags=[rasa-sdk]): the search works properly 🤷 

The full config is available here: https://github.com/algolia/docsearch-configs/blob/master/configs/rasa.json

☝️ We've currently disabled the search on both Rasa and Rasa X sites because of this. You can access our Pull Request for re-enabling it, with the right configuration set here: https://github.com/RasaHQ/rasa/pull/6776 (Rasa Open Source repository)

The last I heard from your team was from @PLNech who kindly debugged things for us, but sadly it wasn't enough.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= "rasa"

## What is the **current** behaviour?

Cf. above ⬆️ 

## What is the **expected** behaviour?

We expect that when we configure the search like following on our docs site:

```javascript
   searchParameters: {
        'facetFilters': ["tags:rasa"]
   }
```

it only returns results for the Rasa website. And similar behaviour when `tags:rasa-x` facet is selected.

#### What have you tried to solve it?

Reached out to support multiple times.

#### Any quick clues?

I think it's related to the previous config we had in the past, where no facets where present. If you could reset things on your end and re-crawl, that might fix it. I obviously don't have a clue about your exact setup behind the scenes, that's only a guess 😅 

### Any other feedback / questions ?

We've just released Rasa 2.0 and this issue is currently very pressing. It is making the docs site virtually unusable for people because they can't search (and I'm sure that, as people working for Algolia, you can appreciate the need for a search!)

I'm also cc'ing @Shipow here because he reviewed our docs configuration and merged my PRs and he might have an idea of what's going on?

**Comment by Shipow** [comment]
on it

**Comment by Shipow** [comment]
The problem is fixed.
For record:
Definition of start_urls needed a trailing slash. https://github.com/algolia/docsearch-configs/commit/a7de3a14eb0fa3c77e0336d8a569c9d0c7109fd4

**Comment by m-vdb** [comment]
Thanks a lot @Shipow for jumping on this!
