### ISSUE TITLE
Baslerweb search index broken

### ISSUE THREAD

**Issue by wilhelmer** [algolia/docsearch-configs#2573]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `baslerweb`

### Any quick clues?

In commit https://github.com/algolia/docsearch-configs/commit/a83ea21a516ba2bf235a3f83b3e2723a0c8b2fc1, the start/sitemap URL was changed from docs.baslerweb.com to ja.docs.baslerweb.com. Now, search results in our English version are displayed in Japanese. Please change it back to docs.baslerweb.com **as soon as possible**, as this is our primary documentation with thousands of visitors per day.

See https://github.com/algolia/docsearch-configs/commit/a83ea21a516ba2bf235a3f83b3e2723a0c8b2fc1#commitcomment-43333957

Thank you!

**Comment by shortcuts** [comment]
Hi,

On it.
Is this the only change that needs to be done?

**Comment by shortcuts** [comment]
Fixed on #2582

**Comment by wilhelmer** [comment]
We also need an additional config file named `baslerweb_ja` as mentioned in https://github.com/algolia/docsearch-configs/commit/a83ea21a516ba2bf235a3f83b3e2723a0c8b2fc1#commitcomment-43333957.

But I'm glad our main index is now fixed, thanks!

**Comment by shortcuts** [comment]
Ok, I saw the confusion on helpscout then.

I will resolve that ASAP

**Comment by shortcuts** [comment]
@wilhelmer I have answered to you on helpscout with the informations for the japanese documentation (just edited it), let me know if there's any other issue.

**Comment by wilhelmer** [comment]
@shortcuts The `baslerweb` and also the new `baslerweb_ja` config files have different settings for `selectors` and `strip_chars` than the original version. `baslerweb_zh` still has the correct settings.

Please apply the following settings to both `baslerweb` and `baslerweb_ja`:

```json
{
  "selectors": {
    "lvl0": {
      "selector": ".md-tabs__link--active",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": ".md-content h1",
    "lvl2": ".md-content h2",
    "lvl3": ".md-content h3",
    "lvl4": ".md-content h4",
    "lvl5": ".md-content h5",
    "lvl6": ".md-content h6",
    "text": ".md-content p, .md-content li"
  },
  "strip_chars": " .,;:#",
}
```

**Comment by shortcuts** [comment]
Fixed both of the errors in #2584, it looks like they were auto-generated so that might be the issue.

**Comment by wilhelmer** [comment]
@shortcuts Thanks, looking good! Now I only need the API key for `baslerweb_ja` via mail, haven't received it yet. And then I think we're good to go! :-)

**Comment by shortcuts** [comment]
@wilhelmer I sent it a few hours ago, I will re-send it!

**Comment by wilhelmer** [comment]
I only received a new API key for the existing `baslerweb` config file, but that doesn't seem to work with `baslerweb_ja` ...

**Comment by wilhelmer** [comment]
@shortcuts Nope, that doesn't work. Please recheck the config file.

![2020-10-19_16-13-41](https://user-images.githubusercontent.com/2234833/96462728-33ad8880-1226-11eb-9273-5228f75c3e77.png)

**Comment by wilhelmer** [comment]
It's fixed, we have sorted it out via mail. Thank you!
