### ISSUE TITLE
Search not detecting lvl0 selector on some pages

### ISSUE THREAD

**Issue by tomgenoni** [algolia/docsearch-configs#261]
For https://thumbprint.thumbtack.com our `lvl0` selector looks like:
```
"lvl0": {
 "selector": "//*[@data-id='header__links']//a[@data-active='true']",
 "type": "xpath",
  "default_value": "Documentation"
},
```

https://github.com/algolia/docsearch-configs/blob/master/configs/thumbprint.json

When I search for the page title "Using Thumbprint in Sass" — https://thumbprint.thumbtack.com/guide/creating-pages/ — the search result correctly categorizes it under "Guide".

But if I search for the pages titles of the following pages:

- https://thumbprint.thumbtack.com/guide/utility-classes/
- https://thumbprint.thumbtack.com/guide/fonts/
- https://thumbprint.thumbtack.com/guide/philosophy/
- https://thumbprint.thumbtack.com/guide/creating-a-new-icon/

It categorizes them under "Documentation" instead of "Guide". 

In this screenshot "https://thumbprint.thumbtack.com/guide/utility-classes/" is among the results, note that it's categorized under "Documentation"

![screen shot 2017-11-17 at 10 16 07 am](https://user-images.githubusercontent.com/1171072/32962512-9b655398-cb81-11e7-80dd-ca48f339ff92.png)

I've confirmed the `lvl0` xpath works on those pages so am not sure what would have caused it to fail. Maybe your crawler searched cached pages that didn't have this selector available?

**Comment by s-pace** [comment]
Hi Tom,
Thank you for the feedback.
The crawler isn't using any cache. We are doing a total new crawling each 24h. I have checked it and it looks like this issue is solve.
This issue should be because of the time needed to have the crawling done.
Let us know if you need anything.

**Comment by tomgenoni** [comment]
Yes, the issue appears to have resolved itself. What I meant by cache is that it could have been a problem with our site. The Cloudfront cache (which we'll eventually disable) takes about 24 hrs to clear so it's possible the Algolia search script was seeing older versions of some of our pages. 

Thank you for your help! We have a better understanding of how the search config works now.

**Comment by s-pace** [comment]
Thank you for your the amendment. Makes sense.
Glad to help.
Closing it since we are done with it.
