### ISSUE TITLE
[banuba] Docs are not reindexed after `routeBasePath` update

### ISSUE THREAD

**Issue by artemjackson** [algolia/docsearch-configs#2667]
# Do you want to request a **feature** or report a **bug**?

I want to report an **issue**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= banuba

## What is the **current** behaviour?

http://docs.banuba.com/docs/ was renamed to http://docs.banuba.com/face-ar-sdk/ but search results still point to old urls (see screenshot above)

![image](https://user-images.githubusercontent.com/3768221/97534811-b1faef00-19cb-11eb-9f90-f7c5f10749b6.png)

## What is the **expected** behaviour?

Search results should point to new urls

#### What have you tried to solve it?

I've submitted the PR https://github.com/algolia/docsearch-configs/pull/2625 in hope that the docs will be reindexed, but they were not.

**Comment by Shipow** [comment]
Should be fixed with https://github.com/algolia/docsearch-configs/commit/6db64c98810c84460ffcd76247c3aed4d4462b5c
using config file for latest docusaurus version.
