### ISSUE TITLE
[Pulsar website research] Search does not work properly for Pulsar doc website

### ISSUE THREAD

**Issue by Jennifer88huang** [algolia/docsearch-configs#2725]
# Bug

## What is the **current** behaviour?

1. Go to Pulsar 2.6.0 doc website https://pulsar.apache.org/docs/en/2.6.0/pulsar-2.0/
2. Search any key word, no search result is displayed. The following screenshot is just an example.
![image](https://user-images.githubusercontent.com/47805623/98334045-f70ec900-203c-11eb-8765-c1575f5ccc49.png)

## What is the **expected** behaviour?
There should be some results related to the key word search.
When I research with the latest version https://pulsar.apache.org/docs/en/next/pulsar-2.0/, the search works. The following is an example.
![image](https://user-images.githubusercontent.com/47805623/98334255-713f4d80-203d-11eb-8c8b-962d697d0b80.png)

**Comment by shortcuts** [comment]
Hi,

Setting up `language` and `version` variables in your config could help the scraper to get content from you website with the right tags.

I have updated your config accordingly (#2729), you will just need to update your DocSearch instance [like this](https://docsearch.algolia.com/docs/config-file/#using-regular-expressions).
It should be effective in the next 24 hours.

Let me know if there's any issues related to the update,
Have a nice day.
