### ISSUE TITLE
[illumina_nirvana] No results found when using within Docusaurus v2

### ISSUE THREAD

**Issue by MichaelStromberg** [algolia/docsearch-configs#2726]
Hi there,

I registered for a docsearch API key a few months ago, I but didn't have time to start using it with my Docusaurus site until a couple of days ago.

* git repo: https://github.com/Illumina/NirvanaDocumentation
* Algolia configuration settings: https://github.com/Illumina/NirvanaDocumentation/blob/master/docusaurus.config.js
* public URL: https://illumina.github.io/NirvanaDocumentation

I expected there might be a delay in indexing the site, but after 48h there are no responses in my Algolia search window. I compared my `docusaurus.config.js` settings to those used by other sites in the [Docusaurus Showcase](https://v2.docusaurus.io/showcase/), but my settings seemed consistent with how they activated the docsearch plugin.

Any idea what the core issue is? Was the API key deactivated because it wasn't used initially?

**Comment by shortcuts** [comment]
Hi,

As you are moving to DocSearch v3, I have upgraded your config with the needed changes for it to work (#2727).
Please let me know if there's any other issues with it.

It should be effective in the next 24 hours!
Have a nice day

**Comment by MichaelStromberg** [comment]
Everything works brilliantly now - you guys are amazing!
