### ISSUE TITLE
[tailwindcss] Missing results for query "color"

### ISSUE THREAD

**Issue by karakanb** [algolia/docsearch-configs#2805]
When I run a search with the keyword `color`, I am not able to find anything on TailwindCSS docs.

![image](https://user-images.githubusercontent.com/16530606/99606221-9c487a80-2a09-11eb-99a7-01c12b6036b3.png)

**Comment by pajoda** [comment]
https://github.com/algolia/docsearch-configs/issues/2803
https://github.com/algolia/docsearch-configs/issues/2804

I think one issue is enough. The search does not return any results at the moment. Might be related to the release of 2.0, maybe they just polished some additional parts of the docs and are re-indexing.
