### ISSUE TITLE
[tailwindcss] Missing results for query "Max-width"

### ISSUE THREAD

**Issue by sgoehringer** [algolia/docsearch-configs#2815]
I noticed a series of widths not returning in the search.  Keep up the great work!

<img width="816" alt="Screen Shot 2020-11-18 at 9 45 45 PM" src="https://user-images.githubusercontent.com/1117403/99614460-8a55e000-29e7-11eb-9680-eb7652362c11.png">

**Comment by KeenStratium** [comment]
Looks like anything can't be search, this started with their new UI design of the site
