### ISSUE TITLE
[tailwindcss] Missing results for query "margin"

### ISSUE THREAD

**Issue by jefferyxhy** [algolia/docsearch-configs#2821]
the search is almost broken, can not even get any results for any other search, such as: "padding", "font", "grid" etc.

**Comment by KeentDev** [comment]
Even the v1 search is now broken, i am more surprised the "Let us know" link redirects us to algolia's repo instead of Tailwindcss' as this is more of Tailwind v2 upgrade issue than algolia's end.

**Comment by mechelon** [comment]
Same here.
