### ISSUE TITLE
[taro] Missing results for facetFilters

### ISSUE THREAD

**Issue by honlyHuang** [algolia/docsearch-configs#2846]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=taro

## What is the **current** behaviour?

I used Docusaurus contextual Search, it need add `docusaurus_tag` to `configs/taro.json ` like this

```
"attributesForFaceting": [
      "language",
      "version",
      "type",
      "docusaurus_tag"
    ],
```

so I got a PR #2763 , now has no result for searching，such as #2790 #2785 #2784

when searching, the request like this

![image](https://user-images.githubusercontent.com/3080820/99643490-b3c64880-2a87-11eb-9925-70330b472b9c.png)

and the docs already has meta

![image](https://user-images.githubusercontent.com/3080820/99643939-449d2400-2a88-11eb-88ac-b06c9f8f7921.png)

What should I do?

**Comment by shortcuts** [comment]
Hi,

Closing this as it has been fixed.

Have a nice day
