### ISSUE TITLE
Searching for QueryClientProvider results in nothing 

### ISSUE THREAD

**Issue by qikevinjkw** [algolia/docsearch-configs#2854]
To reproduce: 
Click the search bar at the top and search 'QueryClientProvider', it'll show no results even though it's in the docs at https://react-query-beta.tanstack.com/reference/QueryClientProvider

Same error for 'queryclient'

**Comment by R1234321n** [comment]
> To reproduce:
> Click the search bar at the top and search 'QueryClientProvider', it'll show no results even though it's in the docs at https://react-query-beta.tanstack.com/reference/QueryClientProvider
> 
> Same error for 'queryclient'

**Comment by shortcuts** [comment]
Hi,

Closing this as it has been fixed.

Have a nice day
