### ISSUE TITLE
Why delete babeljs_cn ？

### ISSUE THREAD

**Issue by QC-L** [algolia/docsearch-configs#287]
Hey, guys! I'm the maintainer of the babeljs.cn. I found that the docsearch of babeljs_cn was deleted, but I don 't know why. Please tell me why and how to solve it.
commit: https://github.com/algolia/docsearch-configs/commit/e0cc0b80914b9340f2bc4aa28112a7aa5de99ff2

**Comment by maxiloc** [comment]
Hey, not sure what happened, sorry about that. I recreated the config this morning, and you should have the new key in your inbox

**Comment by QC-L** [comment]
Thanks.
