### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Morriz** [algolia/docsearch-configs#2944]
Hi, we were given a key for our doc site, but the queries return no data unfortunately:

https://redkubes.github.io/otomi/

Can you help us get this sorted?

Thanks again,

Maurice

**Comment by shortcuts** [comment]
Hi,

This should be fixed in https://github.com/algolia/docsearch-configs/pull/2948
You should see changes in the next 24 hours!

Have a nice day

**Comment by Morriz** [comment]
We got data :) Thanks!
