### ISSUE TITLE
[shlink] mostly empty results

### ISSUE THREAD

**Issue by acelaya** [algolia/docsearch-configs#2945]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=shlink

## What is the **current** behaviour?

The search results have started to display a lot of text-less entries.

The links work, and take you to relevant places, but they just have no text.

See the screenshot.

![Screenshot_20201201-082840](https://user-images.githubusercontent.com/2719332/100710380-ea696080-33af-11eb-8ea6-93ae4517b06e.png)

I guess I have changed something in the structure, and the crawler is now unable to determine the titles. However, I'm not sure how to debug it.

**Comment by shortcuts** [comment]
Hi,

The crawler depends on your [config file](https://github.com/algolia/docsearch-configs/blob/master/configs/shlink.json), as it looks like your structure changed (js rendering, no more h1 etc.), an update is needed.

I've deployed a fix here that should solve your issue: https://github.com/algolia/docsearch-configs/pull/2949

Feel free to update it and open a new PR if you want to leverage it!

Have a nice day

**Comment by acelaya** [comment]
It works like a charm now. Thanks a lot for the support quick fix.
