### ISSUE TITLE
[wpgraphql] Index not updated in 12 days

### ISSUE THREAD

**Issue by jasonbahl** [algolia/docsearch-configs#2953]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `wpgraphql`

## What is the **current** behaviour?

When searching on www.wpgraphql.com content nested under from `/extension-plugins/`, `/developer-reference/`, `/actions/`, `/filters/`, and `/recipes/` are not returned in search results. 

For example, a search for `register_graphql_field` returns 2 results (see screenshot): 

![Screen Shot 2020-12-01 at 9 22 42 AM](https://user-images.githubusercontent.com/1260765/100767303-d6752d00-33b6-11eb-8ab6-a98465d045a3.png)

But neither of them are the documentation page for the `register_graphql_field` function found here: https://www.wpgraphql.com/functions/register_graphql_field/

## What is the **expected** behaviour?

I expect to see results for content under the `/extension-plugins/`, `/developer-reference/`, `/actions/`, `/filters/`, and `/recipes/` sections in the search results. 

#### What have you tried to solve it?

I opened this PR (https://github.com/algolia/docsearch-configs/pull/2853) but it's been 12 days and no change in behavior.

### Any other feedback / questions ?

Also, related to #2853, I attempted to update how the headings in the docsearch UI appear. Right now they show "Documentation > Documentation > Documentation" and I thought the changes to #2853 would set the hierarchy to use headings from the content so it would show as "Documentation > h1 > h2"

**Comment by jasonbahl** [comment]
@shortcuts it looks like you opened and merged #2952 as I was opening this issue. Thanks for jumping on that so quick!

**Comment by shortcuts** [comment]
@jasonbahl Yup! Should be solved in https://github.com/algolia/docsearch-configs/pull/2952, I'll keep an eye on it but feel free to let me know.

I'll let this issue open until the next crawl!

**Comment by shortcuts** [comment]
Update: Should now be all solved in https://github.com/algolia/docsearch-configs/pull/2973
