### ISSUE TITLE
Update Bootstrap config after 5.0.0-beta1 is released

### ISSUE THREAD

**Issue by XhmikosR** [algolia/docsearch-configs#2997]
Hello!

We are going to release v5.0.0-beta1 in a few hours, and if all goes well, we'll move the docs to the main site. This means that the docsearch URL will need to change from `https://v5.getbootstrap.com` to `https://getbootstrap.com`.

I'll try to update the docs on https://v5.getbootstrap.com/ to redirect to https://getbootstrap.com/, so everything should be OK; worst case scenario, the v5 subdomain will be left at 5.0.0-alpha3 and the search will be broken for a while until we figure out the redirects.

I'm gonna post a comment when we release it; the plan is to do it 2-3 hours after now (around 19:00 GMT+2).

Thanks in advance!

**Comment by shortcuts** [comment]
Hi @XhmikosR,

Thanks for the heads up! 
Feel free to @ me or @Shipow and we will make sure to follow your update!

Good luck with the release

**Comment by shortcuts** [comment]
I've prepared an update in #2998 if everything goes well.

It will also trigger a new crawl task to update everything that has been added between the last crawl and update the links.

Feel free to let me know if there's anything else that should change.

**Comment by XhmikosR** [comment]
@shortcuts @Shipow thanks! We released beta1, can you merge your PR please?

**Comment by shortcuts** [comment]
@XhmikosR PR has been merged, it should run soon, let me know if there's any issue with it!

**Comment by XhmikosR** [comment]
Can you ping us when your index is updated? Right now I still see v5.getbootstrap.com in the search results.

**Comment by shortcuts** [comment]
@XhmikosR The task just finished, you should be able to see the new results now.

**Comment by XhmikosR** [comment]
Perfect, thank you!

**Comment by shortcuts** [comment]
Congrats on the release!

**Comment by XhmikosR** [comment]
@shortcuts @Shipow  could you run the crawler please? We released v4.6.0.

Thanks!

**Comment by shortcuts** [comment]
hi @XhmikosR, done in https://github.com/algolia/docsearch-configs/pull/3278

**Comment by XhmikosR** [comment]
@shortcuts That was fast, thanks! Unfortunately, I still don't get any results on https://getbootstrap.com/docs/4.6/getting-started/introduction/

Does it need a few more minutes maybe?

**Comment by shortcuts** [comment]
@XhmikosR It's around 15k/22k hits now, so it should be finished soon!

**Comment by XhmikosR** [comment]
Perfect, thank you!
