### ISSUE TITLE
Missing search results

### ISSUE THREAD

**Issue by Minhsh** [algolia/docsearch-configs#3003]
#

# Do you want to request a **feature** or report a **bug**? 
A bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=ibm_z_open_editor

## What is the **current** behaviour? 
When users type "ZAPP files" or other words in the search box, no search results or the correct search results are not returned.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
Content that include ZAPP files should be returned.

**Comment by shortcuts** [comment]
Hi,

It looks like our crawler can't retrieve any pages on your website.

Would you be able to add a **sitemap.xml**?

Thanks

**Comment by Minhsh** [comment]
> Hi,
> 
> It looks like our crawler can't retrieve any pages on your website.
> 
> Would you be able to add a **sitemap.xml**?
> 
> Thanks

Hello, thanks for the response! Could you please point me to the instructions on creating a sitemap.xml? I am not quite sure what kind of sitemap.xml is required and how to do that.

**Comment by shortcuts** [comment]
Hi,

It looks like the issue was just using the `/Doc/` endpoint (as it returns a 4040) which is now resolved in: https://github.com/algolia/docsearch-configs/pull/3006

This should be effective in the next 24 hours,
Have a nice day.

**Comment by Minhsh** [comment]
Excellent! It works now. Thanks for the quick fix!
