### ISSUE TITLE
[aptopayments] Missing results for query "card"

### ISSUE THREAD

**Issue by IagoLast** [algolia/docsearch-configs#3010]
I've setup docsearch using docusaurus, but I'm not getting search results. 

This is the branch preview of our docs webpage, the widget is shown but no results are retrieved:

- https://deploy-preview-49--apto-developer-docs.netlify.app/docs/welcome/

Any suggestions? Regards

**Comment by shortcuts** [comment]
Hi @IagoLast,

It looks like something changed in your website structure, please make sure to always keep your config file compliant with it.

I've made an updated here: https://github.com/algolia/docsearch-configs/pull/3013

You should be able to see the changes in the next 24 hours,
Have a nice day!

**Comment by IagoLast** [comment]
Hi @shortcuts still no results :( 

Regarding the config file, docs.aptopayments.com is **client side redirected** to https://docs.aptopayments.com/docs/welcome/ I don't know if that affects.

any suggestions?

**Comment by IagoLast** [comment]
@shortcuts ping

**Comment by shortcuts** [comment]
Hi @IagoLast,

Your website was crawled around 15 hours ago (1500+ hits) without any issues from our side.

Could you please make sure that your DocSearch instance is compliant with [this example](https://v2.docusaurus.io/docs/search/)?

**Comment by IagoLast** [comment]
@shortcuts 

We are using this:

<img width="468" alt="Screenshot 2020-12-14 at 15 59 16" src="https://user-images.githubusercontent.com/2657897/102096764-5bcff700-3e25-11eb-8179-e2f7b86e96e0.png">

I double checked the apiKey is the right one.

**Comment by shortcuts** [comment]
@IagoLast 

It looks like it's working for me: https://deploy-preview-49--apto-developer-docs.netlify.app/docs/welcome/
