### ISSUE TITLE
Security Overview page does not display in search anymore after #3034 update

### ISSUE THREAD

**Issue by ArshRai17** [algolia/docsearch-configs#3045]
# Do you want to request a **feature** or report a **bug**?

bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=solace

## What is the **current** behaviour?
With the change in #3034 the Security Overview page (https://docs.solace.com/Security/Security-Solace.htm), which I wanted on the top (#3028 ) does even visible in the search anymore.

![image](https://user-images.githubusercontent.com/29955404/102092290-e85ec300-3ded-11eb-80bb-b54d4aeaf527.png)

## What is the **expected** behaviour?
The Security Overview page (https://docs.solace.com/Security/Security-Solace.htm) should be ranked on the top when someone searches for the term "security".

#### What have you tried to solve it?
I tried (#3028 ) and @shortcuts added #3034 .

**Comment by shortcuts** [comment]
Hi,

It looks like we can't really do much about this issue, the only way to improve this is to play with the `page_rank`.

As you can see [here](https://docsearch.algolia.com/docs/inside-the-engine/#ranking-records), it depends of where the matching words are located (and which selector level) on your website.

Feel free to tag me in your PR so I can review it faster,
Have a nice day.
