### ISSUE TITLE
[avo] sitemap is not recognized

### ISSUE THREAD

**Issue by tpom6oh** [algolia/docsearch-configs#3121]
# Do you want to request a **feature** or report a **bug**?

Probably a bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= avo

## What is the **current** behaviour?

Here is our config

https://github.com/algolia/docsearch-configs/blob/master/configs/avo.json

I've run the scrapper locally against it and it only picks up the start url and another url that is present on that page 

```
docsearch-scraper % ./docsearch run avo-config.json          
> DocSearch: https://www.avo.app/docs/ 14 records)
> DocSearch: https://www.avo.app/docs/help/troubleshooting 5 records)

Nb hits: 19
```

## What is the **expected** behaviour?

All the urls from the specified sitemap - https://www.avo.app/docs/sitemap.xml - should be crawled 

#### What have you tried to solve it?

Read the docs and it looks like everything is set up correctly to me 🤔

I've tried to remove the start urls configuration and after that change the local crawler actually checked everything in the sitemap.

The pull request is #3122

**Comment by shortcuts** [comment]
Resolved in https://github.com/algolia/docsearch-configs/pull/3122
