### ISSUE TITLE
[dgraph] no search results for dgraph

### ISSUE THREAD

**Issue by bucanero** [algolia/docsearch-configs#3128]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=dgraph

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Steps to reproduce:

-    Go to the docs website https://dgraph.io/docs
-    Go to the FAQ section 
-    Switch the version from the version dropdown on the sidebar, e.g. `v20.07`
-    Go to the search box on the header and type in a query, e.g. `deploy`
-    You will notice that the search returns an empty response

<img width="1412" alt="Screenshot 2020-12-23 at 11 26 55 AM" src="https://user-images.githubusercontent.com/1153055/103243166-b134f980-4937-11eb-91a0-36fa17cf83e7.png">

## What is the **expected** behaviour?

Search should return the expected result if present in the docs for that version

#### What have you tried to solve it?

Checking the dgraph.json config, the file hasn't changed since August.

#### Any quick clues?

No.

### Any other feedback / questions ?

No.

**Comment by shortcuts** [comment]
Hi,

I've updated your config here https://github.com/algolia/docsearch-configs/pull/3134, it should now be fixed, let me know if you can see any changes in the next 24 hours.

Have a nice day.

**Comment by bucanero** [comment]
hello @shortcuts, thanks for your help 👍 
I've just checked and Algolia's search is working again

Happy holidays, cheers!
