### ISSUE TITLE
Search going to a 404

### ISSUE THREAD

**Issue by metmarkosaric** [algolia/docsearch-configs#3159]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= "plausible"

## What is the **current** behaviour?

It seems to be related to our recent change of the docs URL from docs.plausible.io to plausible.io/docs: https://github.com/algolia/docsearch-configs/pull/3135

Right now if I type anything in the search box on https://plausible.io/docs and press enter without choosing one of the immediate results in the popup, I get a 404 like this: https://plausible.io/search?q=hello 

## What is the **expected** behaviour?

The expected behavior is that when I press enter it should go to https://plausible.io/docs/search?q=hello instead.

#### What have you tried to solve it?

Looking at the docs I can't find a way to configure this myself so I'm thinking it's something you can do on your end? Thanks for your help!

**Comment by shortcuts** [comment]
Hi,

The search page is generated on Docusaurus side by [this package](https://v2.docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia/) and is by default located at the root of your website (e.g. `https://plausible.io/search`).

If your `docs` folder is inside your `website` folder you might be able to define a [customDocsPath](https://docusaurus.io/docs/en/site-config#customdocspath-string)

Have a nice day.

**Comment by metmarkosaric** [comment]
thanks @shortcuts!
