### ISSUE TITLE
[patternfly] Bug: searching for lvl0 selector not working

### ISSUE THREAD

**Issue by redallen** [algolia/docsearch-configs#3176]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=patternfly

## What is the **current** behaviour?

Pages like https://www.patternfly.org/v4/components/button and https://www.patternfly.org/v4/components/button/html are not shown in the search results when searching for "Button" despite it being the lvl0 selector.

However pages like https://www.patternfly.org/v4/components/button/design-guidelines are shown.
![image](https://user-images.githubusercontent.com/47335686/103674214-7ee55680-4f4c-11eb-9cc2-0795080ccd9d.png)

## What is the **expected** behaviour?

The search "Button" should show pages that have the lvl0 selector "Button" like https://www.patternfly.org/v4/components/button and https://www.patternfly.org/v4/components/button/html. The lvl1 selector `.pf-c-tabs__item.pf-m-current > a` should be applied to pages like https://www.patternfly.org/v4/components/button/ and https://www.patternfly.org/v4/components/button/html which appear in `sitemap.xml` to display "React | Button" and "HTML | Button" in the search results.

#### What have you tried to solve it?

Double checking the lvl0 and lvl1 selectors work on the pages in question.

#### Any quick clues?

This started happening after removing the explicit https://www.patternfly.org/v4/components/X/react routes that were causing duplicate "React" entries.

Components like "Tabs" work properly through having a "Props > Tabs" ("Props" is an h2, "Tabs" an h3):
![image](https://user-images.githubusercontent.com/47335686/103674514-d8e61c00-4f4c-11eb-8737-abc7052bcfa8.png)

This is confusing because components like "Button" also have a "Props > Button" but do not appear in the search results.

### Any other feedback / questions ?
While I haven't dug into the code, I think that Algolia might only be matching against text. Also, our index may be stale?

I'm considering for React and HTML changing the lvl2 "Examples" header to "Button examples" and seeing how that affects the index. Since it's also included in the `text` selector it may work? Or maybe expanding the text selector to `main` instead of `main #main-content` would be better? Despite reading the documentation I'm not sure which is better or if either would fix this problem.

**Comment by shortcuts** [comment]
Hi,

Our results are "weighted" by a lot of criteria but also matching words. 

On a page like [this one](https://www.patternfly.org/v4/components/button), there's only one match on `Buttons`, compared to the [top hit page](https://www.patternfly.org/v4/components/button/design-guidelines/#button-placement) that match it at least 4 times.

You could update your config and [add more weight](https://www.patternfly.org/v4/components/button/design-guidelines/#button-placement) to pages under the `/components/` URL to help the ranking, or do a small description like on the [Tabs](https://www.patternfly.org/v4/components/tabs/) page to add more matches.

I've removed the text selector on `main #main-content` to make it more specific on `p` and `li` tags to avoid unwanted matches. Keep in mind that having precise selector is better for your search other than selecting a whole bloc.

Your config has been updated (https://github.com/algolia/docsearch-configs/pull/3178) but it should still be tweaked on your side if you want to improve the results.

Hope this helps,
Have a nice day.

**Comment by redallen** [comment]
Thanks @shortcuts !
