### ISSUE TITLE
[activeui] No results in docsearch for versions > 4.3.10

### ISSUE THREAD

**Issue by antoinetissier** [algolia/docsearch-configs#3449]
Hi all, any help would be appreciated with the problem below.

### Config info
`index_name`= activeui
Link to the JSON config: [activeui.json](https://github.com/algolia/docsearch-configs/blob/master/configs/activeui.json)

### Problem
We use docusaurus to generate the documentation for our library.
A new version of the documentation is generated and deployed at a dedicated path for reach official release, e.g.:
- For version 4.3.9: https://activeviam.com/activeui/documentation/4.3.9
- For version 4.3.10: https://activeviam.com/activeui/documentation/4.3.10

When the documentation for a given version is generated, we configure docusaurus to add `docsearch` with `facetFilters` for that version.

The problem is that the queries fired by docsearch return no results for versions that are >= 4.3.10.

### What we have done so far
- When inspecting the network tab after typing something in the searchbar, we see that the `docsearch` query is fired with the proper parameters (including the version `facetFilter`). It just returns no results.
- We have disabled any caching.
- We have compared sitemaps for working versions and not working versions, e.g. https://activeviam.com/activeui/documentation/4.3.9/sitemap.xml and https://activeviam.com/activeui/documentation/4.3.10/sitemap.xml, and they look exactly the same.

### Questions

The problem seems to occur only for the latest versions. Could it be related to a size limit on the index ?

Let me know if you need any more information.

**Comment by shortcuts** [comment]
Hi,

When was the docs of the 4.3.10 and above released? It looks like there's no records matching these versions in your index and our last crawl was 4 hours ago.

I just ran it locally and it seems to work fine.

**Comment by antoinetissier** [comment]
Hi, thank you for the quick answer.

The doc for 4.3.10 was last updated on 2020-09-14.
The latest doc, 4.3.15, was uploaded on 2020-12-03.

**Comment by shortcuts** [comment]
I've just started a new crawl and I can already see results from 4.3.10 and above, as there's around 500k records it might take a while but you should see the changes in the next 24 hours!

Have a nice day

**Comment by antoinetissier** [comment]
Great, thanks ! Is there anything that we can do to help prevent this in the future ? Also, if I need to investigate next time, is there a place where I can see the result ot the latest crawl / the latest index ?

**Comment by shortcuts** [comment]
I'll keep a look on the next crawl tasks to see if there's any inconsistencies, for now I got the same results on 3 crawl tasks but I'll keep investing.

Sorry, we don't give access to this part of the dashboard with the free DocSearch account.

You could try our [run on your own](https://docsearch.algolia.com/docs/run-your-own/) method to see how it works under the hood but considering that you have around 500k records, a free plan won't be enough!
