### ISSUE TITLE
[tailwindcss] Missing results for query "orientation"

### ISSUE THREAD

**Issue by oneWaveAdrian** [algolia/docsearch-configs#3473]
Would it be possible to include the `orientation` media query as documented in

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation

as a state?

Example:

```
<div class="hidden orientation-landscape:block" />
```

**Comment by oneWaveAdrian** [comment]
Yes, no, maybe?

**Comment by shortcuts** [comment]
Closing since wrong repository.

**Comment by oneWaveAdrian** [comment]
@shortcuts I used the tailwind feedback button within the search. This means Tailwind set their docs up the wrong way.
<img width="736" alt="Screenshot 2021-09-08 at 10 28 49" src="https://user-images.githubusercontent.com/8450519/132474586-edb67bd4-65f6-46cd-83fd-a3aab5cdf85e.png">

**Comment by shortcuts** [comment]
This feedback button is related to the search, if a page is missing we can investigate but if it's related to a selector it's better to ask to them directly as it might impact the whole search experience.
