### ISSUE TITLE
Display search results content in the correct format

### ISSUE THREAD

**Issue by ramosmd** [algolia/docsearch-configs#353]
# Do you want to request a **feature** or report a **bug**?

- Feature request
- index name: [gitlab.json](https://github.com/algolia/docsearch-configs/blob/master/configs/gitlab.json)

## What is the **current** behaviour?

The output of `{{{_highlightResult.content.value}}}` shows only text, as if the results were just a paragraph:

![img_197eb6bd7f74-1](https://user-images.githubusercontent.com/14353869/37834456-8402f692-2e8c-11e8-86ca-cf31cd7cea94.jpeg)

## What is the **expected** behaviour?

- Show the headers:

![screen shot 2018-03-23 at 11 23 21](https://user-images.githubusercontent.com/14353869/37834561-c59114ea-2e8c-11e8-839a-4948e23f7f0e.png)

- Display code in code blocks, like Algolia does for their docs:

![img_2a7bf74b1683-1](https://user-images.githubusercontent.com/14353869/37836025-4268de82-2e90-11e8-9499-ca8b69b22eee.jpeg)

#### What have you tried to solve it?

I don't know how to solve this, couldn't find anywhere - I'm probably searching for the wrong query.

@s-pace thoughts?

**Comment by s-pace** [comment]
👋 @ramosmd 

Was it fixed by #347?

Cheers

**Comment by ramosmd** [comment]
@s-pace thanks again! It hasn't been totally fixed yet. There are 2 things here:

1. Display the headers as headers: looks like this was solved \o/
2. Display code in code blocks: we don't have this yet, but you guys do it in Algolia.

How code is displayed in Algolia Docs search results:

![this](https://user-images.githubusercontent.com/14353869/37975629-1e19cbb2-31b6-11e8-8051-b94a13dbc49f.png)


How code is displayed in GitLab Docs search results:

![screen shot 2018-03-27 at 11 54 26](https://user-images.githubusercontent.com/14353869/37975448-bdb6fc36-31b5-11e8-9647-7fe3f2781ee3.png)

So, the question is, how do I display code blocks from the search results?

**Comment by s-pace** [comment]
@ramosmd 

You want to encapsulate the content from your hits within a block right?

Could you show me the code you are using for doing this customised search UI pls?

I will help you from the codebase.

Cheers

**Comment by ramosmd** [comment]
@s-pace not exactly. I found this in the forum: https://discourse.algolia.com/t/do-not-know-how-to-implement-display-search-results-choosing-mustache-template/1928/5 

We have the same problem as the guy from this thread. What I need is that the results that **contain** code blocks to be rendered as code blocks instead of plain text. ;)

**Comment by s-pace** [comment]
@ramosmd 

Thank you for the links. We would need more details on your question on the discourse.

Feel free to reply and to ask us anything

**Comment by s-pace** [comment]
Feel free to reopen if needed
