### ISSUE TITLE
Duplicated search results in VuePress

### ISSUE THREAD

**Issue by guillaumemeyer** [algolia/docsearch-configs#3583]
# Bug: duplicated search results in VuePress

`index_name`=salestimhelpcenter

## What is the **current** behaviour?

When performing a search from our [website](https://developers.salestim.com), the same page appears twice:
![image](https://user-images.githubusercontent.com/1385518/108416564-2a154b00-722f-11eb-9b4d-e59a885bbcb2.png)

## What is the **expected** behaviour?
Each page should be visible once in a search result set.

#### What have you tried to solve it?
I looked at the `stop_urls` option but it doesn't look like it intends to solve this kind of issue.

#### Any quick clues?
VuePress exposes pages automatically with and without the `.html` extension. When looking at the duplicated results, they're targeting the same page but with different URLs:
- https://developers.salestim.com/nocode/power-platform#use-the-salestim-api-with-power-platform
- https://developers.salestim.com/nocode/power-platform.html#use-the-salestim-api-with-power-platform

Maybe the "#" sign at the end of the URL prevents Algolia to identify these pages as the same one...

**Comment by shortcuts** [comment]
Hi @guillaumemeyer,

This update https://github.com/algolia/docsearch-configs/pull/3588 should fix the duplicate hits as it will exclude all URLs ending with `.html`

You should see the changes in the next 24 hours,
Have a nice day!

**Comment by guillaumemeyer** [comment]
That's great, gonna try this

**Comment by guillaumemeyer** [comment]
Works great thanks!
![image](https://user-images.githubusercontent.com/1385518/108625962-024ffe00-744e-11eb-8449-8f36d1a1c207.png)
