### ISSUE TITLE
[numl] broken render for any query

### ISSUE THREAD

**Issue by tenphi** [algolia/docsearch-configs#3606]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= 'numl'

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

1) Open any page with searchbar. https://numl.design/handbook
2) Type any query

The search results are broken.

<img width="567" alt="Screenshot 2021-02-23 at 11 10 52" src="https://user-images.githubusercontent.com/327209/108816791-e07a8680-75c7-11eb-8021-dccdff6fad4e.png">

## What is the **expected** behaviour?

The search results are rendered correct as when I first connected the docsearch.

#### What have you tried to solve it?

I tried several versions.

#### Any quick clues?

Looks like backend returns incorrect data with empty headings. It may somehow break the frontend part.

<img width="288" alt="Screenshot 2021-02-23 at 11 14 06" src="https://user-images.githubusercontent.com/327209/108817004-4404b400-75c8-11eb-9a17-22e1de99586b.png">

**Comment by shortcuts** [comment]
Hi there,

I've tried reducing the delay of the client-side rendering here https://github.com/algolia/docsearch-configs/pull/3609, will see if it helps.

The issue is due to the whole side rendering on client-side, which could lead in a timeout after taking too long to respond.

**Comment by tenphi** [comment]
Hi @shortcuts,

Thanks for the response. I see that the popup window is shown almost instantly. So I not sure that it's the case.

Also, when I set the test config I see that the response is different with correct headings:

<img width="277" alt="Screenshot 2021-02-23 at 14 31 23" src="https://user-images.githubusercontent.com/327209/108837825-e1b9ac80-75e3-11eb-92a8-d0d69debab1f.png">

I believe that the correct response will fix the issue.

**Comment by shortcuts** [comment]
> Thanks for the response. I see that the popup window is shown almost instantly. So I not sure that it's the case.

The client-side rendering issue I talk about is when we try to crawl your website.

I'll try to add more exclusion like these pages https://numl.design/reference/behaviors/focus where content isn't available yet to reduce the workload.

**Comment by tenphi** [comment]
Thanks! I got it now. Yes, we're still rolling out and a lot of pages are just placeholders with basic information.

All pages are SSR so there is no need to wait for the content. All selectors are available from the start.

**Comment by shortcuts** [comment]
Fixed it in https://github.com/algolia/docsearch-configs/pull/3611, good results are now available on your site!

**Comment by tenphi** [comment]
Thanks a lot! It works now and does it very well! 👍
