### ISSUE TITLE
[mediamachine] Missing results for query "watermark"

### ISSUE THREAD

**Issue by urjitbhatia** [algolia/docsearch-configs#3645]
Hi, we're not seeing any results at all for our site. Is there anything we need to fix on our end?

We appreciate your time and effort in helping us fix this - let me know if I can provide more information to help debug.

Thanks,

**Comment by shortcuts** [comment]
Hi there,

Answered in https://github.com/algolia/docsearch-configs/issues/3635, closing for duplicate
