### ISSUE TITLE
Update QA Wolf config?

### ISSUE THREAD

**Issue by flaurida** [algolia/docsearch-configs#3678]
Hi there 👋 thanks for the awesome project!

We (QA Wolf) moved our docs site to https://www.qawolf.com/docs and would like to update [our config](https://github.com/algolia/docsearch-configs/blob/master/configs/qawolf.json) somehow.

We are no longer using Docusaurus so realize we may have to make a few changes on our end. If you have any guidance, happy to submit a PR updating the config.

Thanks 🐺

**Comment by shortcuts** [comment]
Hi @flaurida,

I've applied the changes in https://github.com/algolia/docsearch-configs/pull/3685

Have a nice day!

**Comment by flaurida** [comment]
Hi @shortcuts thanks so much 😊 likewise have a nice day!
