### ISSUE TITLE
Indexing ellipsis

### ISSUE THREAD

**Issue by jayhesselberth** [algolia/docsearch-configs#373]
# Do you want to request a **feature** or report a **bug**?

More feature than bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pkgdown

## What is the **current** behaviour?

May R functions make use of ellipsis (`...`) to catch arguments in function calls. In a pkgdown documentation website these appear in the Argument list (see third argument on [this page](http://valr.hesselberthlab.org/reference/bed_map.html)).

We capture most arguments and their values with the current docsearch pkgdown config, but ellipsis are not indexed because they are considered punctuation.

## What is the **expected** behaviour?

I'd like `...` to be included in search results as an argument value.

#### What have you tried to solve it?

 I have tried including a period (`.`) in `separatorsToIndex` but the ellipsis are still not indexed.

**Comment by s-pace** [comment]
👋 @jayhesselberth ,

Thank you for this challenge.

Would you try to use this character instead  [`Unicode Character 'HORIZONTAL ELLIPSIS …`](https://www.fileformat.info/info/unicode/char/2026/index.htm). We will use this character as a `separatorsToIndex` and then replace the ` . . .`  with this specific character at the query time thanks to [queryhook](https://community.algolia.com/docsearch/documentation/docsearch-autocomplete/configuring-the-search/#queryhook)

Please note that the website `pkgdown` doesn't contain this argument. You can test it on `valr`. The `separatorsToIndex` was working but with too much side effect.

Let us know if you think it worths it.

**Comment by s-pace** [comment]
Exactly you got it 💯

**Comment by s-pace** [comment]
Looks solved, Feel free to re-open if needed
