### ISSUE TITLE
[pnpm] Missing results for query "install"

### ISSUE THREAD

**Issue by zkochan** [algolia/docsearch-configs#3740]
Getting no search results since migrated the [pnpm docs](https://pnpm.js.org/) to docusaurus 2. Even though the configuration was updated: https://github.com/algolia/docsearch-configs/pull/3714

**Comment by shortcuts** [comment]
Hi,

Some `attributesForFaceting` were missing in your config, it will be fixed in https://github.com/algolia/docsearch-configs/pull/3758

You should see the changes in the next 24 hours!

**Comment by zkochan** [comment]
The search is still not working.

**Comment by shortcuts** [comment]
It looks like you are sending wrong `facetFilters`, `facetFilters: ["language:LANGUAGE","version:VERSION"]"}]}`, please see the network tab.

Below are the `facetFilters` available for your index
![Screenshot 2021-03-10 at 11 08 24](https://user-images.githubusercontent.com/20689156/110612950-fa53c600-8190-11eb-9110-450ab96afda9.png)

**Comment by zkochan** [comment]
Thanks, fixed by updating the configs in docusaurus: https://github.com/pnpm/pnpm.github.io/commit/6d3bd1d531ef68ae0b637777906566c3e2c84485

**Comment by shortcuts** [comment]
This will create duplicate results from all the version on your search, adding the [contextualSearch](https://v2.docusaurus.io/docs/search#contextual-search) key will grab the filters from the meta tags `docsearch:version - docsearch:language - docsearch:docusaurus_tag`

**Comment by zkochan** [comment]
Yes, already added it. Works perfectly. Thank you for the support!
