### ISSUE TITLE
Pages are not indexed since domain transfer

### ISSUE THREAD

**Issue by reindert-vetter** [algolia/docsearch-configs#3769]
## Do you want to request a **feature** or report a **bug**?
Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= confetti-framework

#### Search results do not refer to a page on confetti-framework.com
The website has been moved from https://confetti-framework.github.io/docs to https://www.confetti-framework.com. After this, the links of the results were still referred to the old website.
1. https://www.confetti-framework.com/docs/digging-deeper/commands.html
![image](https://user-images.githubusercontent.com/16726304/110696603-914d6c00-81eb-11eb-8c90-46c089d5f298.png)

#### Pages are not indexed
1. Go to https://www.confetti-framework.com/docs/digging-deeper/commands.html
2. Click on the search bar
3. Search for, for example, Baker:
![image](https://user-images.githubusercontent.com/16726304/110695596-60206c00-81ea-11eb-8eeb-0f618fa6dbd4.png)

Chapter Commands has been new for a few weeks and the pages cannot be found. Just like any other new content.

## What is the **expected** behaviour?

- Search result must link to a page on confetti-framework.com
- Pages must be reindexed

#### What have you tried to solve it?
Adjustment made in this or: https://github.com/algolia/docsearch-configs/pull/3468. But that did not help.

#### Any quick clues?
Either a setting has to be changed by Algolia, or I have to be registered again with a new index_name.

### Any other feedback / questions ?
Thanks for providing this service! 🤗

**Comment by shortcuts** [comment]
Hi! 

Fixed in https://github.com/algolia/docsearch-configs/pull/3773

You should see the changes in the next 24 hours :D
