### ISSUE TITLE
facetFilters not working

### ISSUE THREAD

**Issue by 1ceb3rg** [algolia/docsearch-configs#3800]
# Do you want to request a **feature** or report a **bug**?
Bug
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=testarchitect

## What is the **current** behaviour?

When facetFilters are included in the query, no results are returned
## What is the **expected** behaviour?
Faceted results are returned 

#### What have you tried to solve it?
Editing the query, running the query with postman

#### Any quick clues?
It stopped working in the past day or 2.

### Any other feedback / questions ?
I've temporarily fixed it by using transformData to facet locally on docs.testarchitect.com , so please test with the version here https://docs-stage1.testarchitect.com/dev/

**Comment by shortcuts** [comment]
Hi,

I'm not yet sure why the facets were not available anymore, did you made any changes on your website yesterday?

Just ran it locally and it worked perfectly, I've updated it here: https://github.com/algolia/docsearch-configs/pull/3801

You should see the changes in the next 24 hours, feel free to let me know if still see an issue
