### ISSUE TITLE
[mediamachine] Missing reindexing

### ISSUE THREAD

**Issue by urjitbhatia** [algolia/docsearch-configs#3850]
Hi, we changed our site navigation recently and don't see re-indexed search results. Do we need to do something to re-trigger indexing?

Thanks,

**Comment by shortcuts** [comment]
Hi @urjitbhatia, it looks like [your config](https://github.com/algolia/docsearch-configs/blob/master/configs/mediamachine.json) isn't compliant anymore. 

You can update the `start_urls` and `selectors` and tag me on the pull request once it's done! :D
