### ISSUE TITLE
[vitejs] Missing results for query "cn.vitejs.dev"

### ISSUE THREAD

**Issue by ShenQingchuan** [algolia/docsearch-configs#3854]
Dear docsearch:
I am the repo manager of https://github.com/vitejs/docs-cn , I did provide a config for the vitepress:

```js
algolia: {
  apiKey: 'b573aa848fd57fb47d693b531297403c',
  indexName: 'vitejs',
  algoliaOptions: {
    'facetFilters': ["tags:cn"]
  },
},
```

Vitepress has a built-in support to delegate option properties from its own config file, as you can see, the `algoliaOptions` filed.

https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/components/AlgoliaSearchBox.vue#L58

Here is some code snippets that I found in Vitepress source code, indeed I'm sure I may set the config keys in the right place.

but someone gave me a guide tour with Email, he has helped me set a new `vitejs.json` with gist and mentioned that I need to send a Pull Request (maybe just here?)

I don't know what to do next without Email guiding later...

gist here: https://gist.github.com/shortcuts/eca47c5a452649061d2b63e53bc64a22

**Comment by shortcuts** [comment]
Hey, that was me :D 

Now with this config, you'll be able to use the same credentials on both domains, with the following `algoliaOptions` 

| cn results        | en results           |
| ------------- |:-------------:|
| `algoliaOptions: { 'facetFilters': ['tags:cn'] }`      | `algoliaOptions: { 'facetFilters': ['tags:en'] }`|

Feel free to let me know if there's any issue,
You should see the changes in the next 24 hours!
