### ISSUE TITLE
[modelica] Specification search no longer returns any hits

### ISSUE THREAD

**Issue by beutlich** [algolia/docsearch-configs#3856]
# Do you want to request a **feature** or report a **bug**?

It seems like a sudden misconfiguration issue.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=modelica

## What is the **current** behaviour?

* Go to https://beutlich.github.io/MLS/index.html
* Type something in the search field
* Observation: No search hits at all

## What is the **expected** behaviour?

* Search should return the corresponding hits (as was the case until 23rd of March)

#### What have you tried to solve it?

* Checked if modelica.json was touched recently.

#### Any quick clues?

* Actually no, sorry.

### Any other feedback / questions ?

@HansOlsson FYI

**Comment by shortcuts** [comment]
Hi,

Your config is missing the following option to make the `tags` works

```json
"custom_settings": {
  "attributesForFaceting": [
    "tags"
  ]
},
```

Feel free to @ me once the PR is opened! :D

**Comment by beutlich** [comment]
@shortcuts Just created #3858 with your proposed change. Thank you.

**Comment by beutlich** [comment]
@shortcuts Can you please reopen and check again why it is still failing? Thank you very much,

**Comment by shortcuts** [comment]
Hi @beutlich,

As your index is around 600k hits, it is quite long to make it complete a full crawl. It looks like there was an issue mid-task, I'll try to see what's the cause

**Comment by shortcuts** [comment]
@beutlich everything should now be up and working

**Comment by beutlich** [comment]
Confirmed. Thank you.
