### ISSUE TITLE
[prebid] No results for content where configuration URL ends in `.html` and content is assigned to tag

### ISSUE THREAD

**Issue by bookwyrm** [algolia/docsearch-configs#3989]
# Do you want to request a **feature** or report a **bug**?
Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=prebid

## What is the **current** behaviour?

When searching, results for pages with a configuration URL value that ends in `.html` and are assigned to a tag are not included in the results.

### Failing search that should return results
```
curl -X "POST" "https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.30.0%3Bdocsearch.js%202.6.3&x-algolia-application-id=BH4D9OD16A&x-algolia-api-key=e9e0827a8769cc3797d1d75add431a5c" \
     -H 'Connection: keep-alive' \
     -H 'Pragma: no-cache' \
     -H 'Cache-Control: no-cache' \
     -H 'Accept: application/json' \
     -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36' \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -H 'Origin: http://127.0.0.1:8080' \
     -H 'Referer: http://127.0.0.1:8080/' \
     -H 'Accept-Language: en-US,en;q=0.9' \
     --data "{\"requests\":[{\"indexName\":\"prebid\",\"params\":\"query=pbjs&hitsPerPage=10&facetFilters=%5B%22tags%3Aapi-reference%22%5D\"}]}"
```

The `api-reference` tag is assigned to [https://docs.prebid.org/dev-docs/publisher-api-reference.html](https://docs.prebid.org/dev-docs/publisher-api-reference.html) in the prebid config and that page includes an `h2` element with the text "pbjs".

### Search that returns unexpected results
```
curl -X "POST" "https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.30.0%3Bdocsearch.js%202.6.3&x-algolia-application-id=BH4D9OD16A&x-algolia-api-key=e9e0827a8769cc3797d1d75add431a5c" \
     -H 'Connection: keep-alive' \
     -H 'Pragma: no-cache' \
     -H 'Cache-Control: no-cache' \
     -H 'Accept: application/json' \
     -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36' \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -H 'Origin: http://127.0.0.1:8080' \
     -H 'Referer: http://127.0.0.1:8080/' \
     -H 'Accept-Language: en-US,en;q=0.9' \
     --data "{\"requests\":[{\"indexName\":\"prebid\",\"params\":\"query=multiple&hitsPerPage=10&facetFilters=%5B%22tags%3Afaq%22%5D\"}]}"
```

The `faq` tag includes two different URLs in the configuration file:

* https://docs.prebid.org/faq/
* https://docs.prebid.org/dev-docs/faq.html

However, when searching for the term `multiple` we only see results under the first URL, not the second URL even though the word "multiple" is present in the 2nd URL (ending in `.html`)

## What is the **expected** behaviour?

I would expect to see results for URLs that end in `.html` in the configuration file.

#### What have you tried to solve it?

We've tried searching with and without facetFilters and using different search terms.

#### Any quick clues?

Sorry, no

### Any other feedback / questions ?

We used tags in this issue to limit results and validate findings but would expect correct results to be returned no matter if results are filtered on tag or not.

**Comment by shortcuts** [comment]
Hi,

Sorry for the delay.

As the `scrape_start_urls` option was set to `false` in your config, this URL was excluded. 

It should be fixed in https://github.com/algolia/docsearch-configs/pull/4004.
