### ISSUE TITLE
[tailwindcss] Missing results for query "scrollbar"

### ISSUE THREAD

**Issue by RAMKUMARDANE** [algolia/docsearch-configs#3993]
scrollbar pseudo selectors css are very useful, kindly make them available for the users

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_custom_scrollbar
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

**Comment by shortcuts** [comment]
Closing since wrong repository.
