### ISSUE TITLE
[tailwindcss] Missing results for query "priority"

### ISSUE THREAD

**Issue by Mr-LJQ** [algolia/docsearch-configs#4162]
![image](https://user-images.githubusercontent.com/50946526/121113773-30aee900-c845-11eb-80dd-947ca1a01914.png)
This is the case. I hope that the priority of newly added classes can be higher than that of ordinary classes. Is there any convenient way to do it? For example, add a prefix "prior:" in front of it.

**Comment by shortcuts** [comment]
Closing since wrong repository
