### ISSUE TITLE
[netlify_d017bb9a-2fd6-4648-8b11-d67021355c27_master_all] Missing results for query "set"

### ISSUE THREAD

**Issue by HugoZaca** [algolia/docsearch-configs#4171]
The deploy has no issues.

4:07:08 PM: Algolia Netlify plugin started
4:07:08 PM: Sending request to crawl https://crawler.algolia.com/api/1/netlify/crawl
4:07:09 PM: API answered: 200

But the serch does not retrieve results

**Comment by shortcuts** [comment]
Hi @HugoZaca,

This seems to be related to the [Crawler](https://www.algolia.com/products/crawler/) and not DocSearch.
