### ISSUE TITLE
[docsearch]: The hit URL property is appended wrongly

### ISSUE THREAD

**Issue by adenekan41** [algolia/docsearch-configs#4203]
# Do you want to request a **feature** or report a **bug**?
- [x] **Bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= magiclabs_magic

## What is the **current** behaviour?

```
hit: {
	url: "/docs/docs/client-sdk/react-native/get-started"
}
```

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
```
hit: {
	url: "/docs/client-sdk/react-native/get-started"
}
```

#### What have you tried to solve it?
- I just replaced the `/docs/docs` with `/docs` as a temporary fix in the hit component.

**Comment by shortcuts** [comment]
Hi,

It looks like our scarper retrieves the right URLs.
However, it seems that you are running an outdated version of DocSearch, see the UA sent with the queries
> Algolia for JavaScript (4.9.1); Browser (lite); docsearch (1.0.0-alpha.14); autocomplete-core (1.0.0-alpha.28)

This is an issue with the alpha tag on NPM, you can find the correct latest version here: https://www.npmjs.com/package/@docsearch/js/v/3.0.0-alpha.36

Hope this solves your issue!
