### ISSUE TITLE
[Milvus] Language setting is not working

### ISSUE THREAD

**Issue by nameczz** [algolia/docsearch-configs#4211]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= milvus

## What is the **current** behaviour?
1. setting meta infomation in milvus.io. Like:
<meta name="docsearch:language" content=“zh-cn" data-react-helmet=“true">

<meta name="docsearch:version" content="v1.1.0" data-react-helmet=“true">

2. When language is en , DocSearch is work perfect.

3. But when language is zh-cn, search result is always empty.

4. You can have a try on our dev site. https://milvus-io-dev.azurewebsites.net/cn/docs/v1.1.0/overview.md

## What is the **expected** behaviour?
We can search when language is zh-cn and en.

#### What have you tried to solve it?
we tried add attribute lang='zh-cn' in html tag.

#### Any quick clues?
How to change milvus.json in this repo?

**Comment by shortcuts** [comment]
Hey,

Thanks for opening the issue and implementing DocSearch meta tags :D

Here's the [config I've used](https://gist.github.com/shortcuts/501118e1096db88287a2a75f9b7df2a2), and it seems to work fine! 

The available facets:
![Screenshot 2021-06-18 at 08 53 57](https://user-images.githubusercontent.com/20689156/122519408-b9cada80-d012-11eb-85bf-6ec192704579.png)

Feel free to open the PR with the new config once it seems good on your side!

**Comment by nameczz** [comment]
Hi, thank you for you reply.

[config you used](https://gist.github.com/shortcuts/501118e1096db88287a2a75f9b7df2a2) is quite different with https://github.com/algolia/docsearch-configs/blob/master/configs/milvus.json.

It makes me confused, if i need to add new version v2.0, do i need to open pr for milvus.json?

Is attribute lang in html tag related to docsearch?

I tried language:cn and language: zh-cn in facetFilters, both return no results.
![image](https://user-images.githubusercontent.com/20559208/122539092-cc1c3700-d059-11eb-9a60-b9bf2b2cfc64.png)

How can i do to fix this?

**Comment by shortcuts** [comment]
Hey,

Since you've implemented to DocSearch meta tags, you don't need them in your config anymore: [doc](https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags)

After opening a pull requestion to update your config to [the one I've put above](https://gist.github.com/shortcuts/501118e1096db88287a2a75f9b7df2a2), you'll be able to use the `language` and `version` you see in the screenshot.

**Comment by nameczz** [comment]
Thanks, i'll open a pull request to do it.
