### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by singleDogZhanghan** [algolia/docsearch-configs#4289]
Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by shortcuts** [comment]
Hi, could you please specify which index is concerned by this error?

**Comment by singleDogZhanghan** [comment]
In the webpack project, it happens when using async function in vuex. Some solutions are to use the babel-plugin-transform-runtime plugin, but I don’t know how to configure it in vite

**Comment by shortcuts** [comment]
You should open this issue on the [webpack repository](https://github.com/webpack/webpack), this one is only related to the search on the website! sorry
