### ISSUE TITLE
[Milvus.io] Docsearch is not working 

### ISSUE THREAD

**Issue by nameczz** [algolia/docsearch-configs#4302]
# Do you want to request a **feature** or report a **bug**?
bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= milvus

## What is the **current** behaviour?
docsearch is working before. 
But today is not working.
I checked meta tag and query is correct.

## What is the **expected** behaviour?
Docsearch is working 

#### What have you tried to solve it?
I checked meta tag and query is correct.

**Comment by nameczz** [comment]
Still not working today.. Any advices?

**Comment by shortcuts** [comment]
Hi,

It seems that you are sending `facetFilters` in your query but none of these `facets` are retrieved from the config file itself.

Here's some documentation on how to implement and/or retrieve `facets` and set them as searchable!

- With meta tags: https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
- With RegExes: https://docsearch.algolia.com/docs/config-file/#using-regular-expressions

Feel free to open a pull request once done! :D

**Comment by nameczz** [comment]
Thank for reply!
We created pull request 17 days ago related to #4211 .  And working fine until this weekend.
Also i checked meta docsearch:language and docsearch:version is correct.

**Comment by nameczz** [comment]
Last week i removed meta in url without version like: /docs/overview.md because of search results duplicated.
But meta is still alive in url with version like: /docs/v2.0.0/overview.md.
I don't know it's the reason or not?

**Comment by shortcuts** [comment]
It seems that we now need to wait for the client-side rendered content to retrieve them, is this something expected on your side?

**Comment by nameczz** [comment]
Sure, thanks for your help! Is docsearch retrieve contents every 24 hours?

**Comment by shortcuts** [comment]
A new crawl will be queued after the PR has been merged!

**Comment by nameczz** [comment]
> A new crawl will be queued after the PR has been merged!

Thanks again! Have a good day!
