### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JacProsser** [algolia/docsearch-configs#4324]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= discord-button

changed links from /d/ to /docs/stable so website needs to be re-indexed but how?

**Comment by shortcuts** [comment]
Hey,

You can update your config file: https://github.com/algolia/docsearch-configs/blob/master/configs/discord-button.json

And then open a pull request in this domain, once the PR has been merged, a new crawl will be started!

**Comment by JacProsser** [comment]
what am i supposed to change exactly? it just provides the old links in the searches but i see nothing to change

**Comment by JacProsser** [comment]
?

**Comment by shortcuts** [comment]
Hey @JacProsser, it indeed looks like the config is good. The new URLs will be fetched during next crawl (in the next 24 hours)

**Comment by shortcuts** [comment]
Hey @JacProsser, it indeed looks like the config is good. The new URLs will be fetched during next crawl (in the next 24 hours)

**Comment by JacProsser** [comment]
okay no problem. thank you!

**Comment by JacProsser** [comment]
would you know if it has been reindexed or not? as it isn't done

**Comment by shortcuts** [comment]
Hi, it ran 6 hours ago and it now shows to right URLs
