### ISSUE TITLE
Docusaurus2 search seemingly not re-indexing

### ISSUE THREAD

**Issue by ckipp01** [algolia/docsearch-configs#4333]
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `metals`

## What is the **current** behaviour?

All of the search results are returned with `.html` the same way they were before we migrated to Docusaurus 2. We've waiting a couple days to see if they'd re-index, however it still seems to return the same. This results in a 404 for every single search result. You can see this at our site here: https://scalameta.org/metals/

## What is the **expected** behaviour?

Following the example of Docusauraus and looking at their own site behavior, I'd expect the search results that are returned from Algolia to _not_ have the `.html` ending. The setup that we have [here](https://github.com/scalameta/metals/blob/050316ad47d5abf7966e92d3fd1f6554609e4849/website/docusaurus.config.js#L136-L139) and the setup that they have [here](https://github.com/facebook/docusaurus/blob/f316ff5cd125778c926cc163093ed3ef99d15edc/website/docusaurus.config.js#L324-L328) is identical minus the contextual search, which we don't need since our site isn't versioned. Notice that on their site https://docusaurus.io/, the search results are not returned with `.html`.

#### What have you tried to solve it?

I've tried changing around different redirect rules from Docusaurus and nothing seems to change the behavior of how the search results are returned.

I tried chatting to the Docusaurus folks on their Discord, but didn't get any help.

Thank you! Let me know if there is something that could be causing this or something else you can think of to try. Maybe even forcing a re-index might help.

**Comment by shortcuts** [comment]
Hi,

The first issue I see is your config is still using the Docusaurus v1 template: https://github.com/algolia/docsearch-configs/blob/master/configs/metals.json

You can update it by following the [docusaurus v2 template](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json) config, basically copy anything from `selectors` (included) to `conversation_id` (excluded), and then open a PR on this repository (which will trigger a new crawl).

Anything should be solved after that :)

**Comment by ckipp01** [comment]
Ahhhh, ok! I saw where it mentioned the template change, but totally didn't register that it was an actual file in this repo. Just shot in the pr. Thanks!
