### ISSUE TITLE
Broken "checker" link in README for this repo

### ISSUE THREAD

**Issue by platinumazure** [algolia/docsearch-configs#439]
# Do you want to request a **feature** or report a **bug**?

Bug (albeit only in documentation).

## What is the **current** behaviour?

Click on the "checker" link in the README. Link targets a `#checker` section in the README that doesn't exist, so the link has no effect. (Ctrl-F to find "checker", it's the only instance)

## What is the **expected** behaviour?

Hopefully it would link to a place with information about the `checker`. :smile:

#### What have you tried to solve it?

Nothing, because I don't know where to find info about the `checker`. If I knew where the info could be found, I would gladly write a PR.

### Any other feedback / questions ?

Thanks, but no.

**Comment by s-pace** [comment]
👋 @platinumazure 

Thank you for sharing. We try to maintain the [documentation in the dedicated website](https://community.algolia.com/docsearch/documentation/docsearch-scraper/config-options/)

Happy to help if you need anything.

Have a nice day.
