### ISSUE TITLE
[veui] Missing correct results for query "Uploader"

### ISSUE THREAD

**Issue by Justineo** [algolia/docsearch-configs#4404]
Current search result:

![image](https://user-images.githubusercontent.com/1726061/126932858-584f2b99-a3d9-4b19-b02b-c9cde1d8f7bb.png)

It should be a `lvl0` heading according the current config:

https://github.com/algolia/docsearch-configs/blob/93d6e217d54ff31d19ae2c601d062e830350a44a/configs/veui.json#L10-L14

![image](https://user-images.githubusercontent.com/1726061/126932792-9a338da9-56e6-4874-9980-0db834a30e09.png)

**Comment by Justineo** [comment]
@shortcuts Sorry to bother, do you know anybody we can consult about this issue? I'm pretty sure I got the config right as other pages got indexed correctly.

**Comment by shortcuts** [comment]
Hey @Justineo,

For missing results/pages, we recommend either adding a sitemap to your config and/or using our [`js_render`](https://docsearch.algolia.com/docs/config-file/#js_render-optional) option to handle client-side rendered content

**Comment by Justineo** [comment]
Your mention of the `js_render` option reminded me that I found that the `Uploader` page wasn't outputting static content properly, which is why it wasn't indexed. So the problem isn't on docsearch's side. Thank you!
