### ISSUE TITLE
[formatjs] Missing results for query "FormatXMLElementFn"

### ISSUE THREAD

**Issue by crccheck** [algolia/docsearch-configs#4428]
What is it? It's _in_ the docs multiple times. Is search not a fulltext search?

**Comment by shortcuts** [comment]
It searches based on the selectors of the config: https://github.com/algolia/docsearch-configs/blob/master/configs/formatjs.json

If the result is not found, it's probably not indexed at all. Could you point which page this element appears?

**Comment by crccheck** [comment]
https://formatjs.io/docs/intl-messageformat#formatvalues-method ended up answering my question about what `FormatXMLElementFn` means.

I already closed the page, but let me try to find where `FormatXMLElementFn` is... if only I could search for it...

**Comment by crccheck** [comment]
aha, web search re-found it for me. Twas yonder https://formatjs.io/docs/react-intl/api/#usage where I was trying to figure out what  `FormatXMLElementFn` meant and how to use it.

> We support embedded XML tag in the message, e.g this is a <b>strong</b> tag. This is not meant to be a full-fledged method to embed HTML, but rather to tag specific text chunk so translation can be more contextual.
https://formatjs.io/docs/intl-messageformat/#formatvalues-method

**Comment by shortcuts** [comment]
Code blocks are not indexed by default, in order to avoid creating noise around regular query.

Since this is more of a documentation concern, I think you should open the issue on their repository, to let them decide to either index code blocks, or document `FormatXMLElementFn`.
