### ISSUE TITLE
[ActiveUI] Missing results for any query across all versions.

### ISSUE THREAD

**Issue by messaooudi** [algolia/docsearch-configs#4461]
The search doesn't yield any results across all versions ( 5.x.x and 4.x.x ).

Current behavior :
Connect to https://activeviam.com/activeui/documentation/5.0.0, or https://activeviam.com/activeui/documentation/4.3.9, type something in the search bar.
It will yield empty results.

Expected behavior:
The search should yield results.

**Comment by messaooudi** [comment]
@shortcuts As you may already know , we just managed to make the search work for `5.x.x` alongside with 4`.x.x`, unfortunately the search is broken for all versions.
Can you please confirm that the last crawling went through, and how many records we have?

**Comment by messaooudi** [comment]
@shortcuts some `4.x.x` still yields results ( see https://activeviam.com/activeui/documentation/4.3.18/index.html ). Did we reach the size limit ?

**Comment by shortcuts** [comment]
Hi, here's all the retrieved versions.

![Screenshot 2021-08-09 at 10 33 38](https://user-images.githubusercontent.com/20689156/128679109-a305334d-0029-4552-a0e4-d3fc633c30e9.png)

It seems that the `5.0.0` version is not retrieved, maybe you should add some entry points of the doc to the `start_urls` like  `https://activeviam.com/activeui/documentation/5.0.0/`

> Can you please confirm that the last crawling went through, and how many records we have?

Yes, 7 hours ago, 243k+

> Did we reach the size limit ?

No size limit for DocSearch users.

**Comment by messaooudi** [comment]
@shortcuts here is what I get when I run the crawling locally
![docsearch](https://user-images.githubusercontent.com/13294350/128707635-f022bb72-22df-4555-a391-dfa191f08a7f.png)

Things to notice : 
- I get far more records : 387K+.
- all the versions specified in the [sitemap.xml](https://s3.amazonaws.com/activeui.activeviam.com/activeui/documentation/sitemap.xml) get crawled , and yield results.
- for the versions that we both have results for, I get more records.

My hint is that for some reason, the crawl stops at some threshold before having the chance to get all the records for the crawled versions (`4.3.5` for example) , and before having the chance to even start crawling some other versions (`5.0.0` for example).

> It seems that the 5.0.0 version is not retrieved, maybe you should add some entry points of the doc to the start_urls like https://activeviam.com/activeui/documentation/5.0.0/

We declare the versions that we want to be crawled in the [sitemap.xml](https://s3.amazonaws.com/activeui.activeviam.com/activeui/documentation/sitemap.xml) file.

**Comment by shortcuts** [comment]
Hey, so I've tried a few crawls and compared the jobs with our biggest indices (1M+ records), it seems that for some reason, yours take longer but it might just be related to the number of pages and/or the page loading time.

Internally, our crawl jobs are in a pool for a few hours (unless they finish before), and if it's not finished during this pool, they will be added to a next one. My guess is that, when switching pools, some content might be skipped or missed.

As we are completely changing the DocSearch infrastructure to a much stable one (all users will have more infos soon), I won't have time to dig on this issue (but will still monitor and try to re run crawls if I see this issue).

One way to solve this would be to group or remove the less used versions from the docs, to reduce the crawl job time. Note that the above issue happened around every 3 crawls.

**Comment by messaooudi** [comment]
Thank you for your feedback.
FYI, today the doc works for both `5.x.x` and `4.x.x`.

> One way to solve this would be to group or remove the less used versions from the docs, to reduce the crawl job time. Note that the above issue happened around every 3 crawls.

I assume if we don't reduce the number of versions ( mainly the 4.x.x ones ), the documentation will be  broken every now and then ? (Until the work you are doing on the DocSearch infrastructure is done).

**Comment by shortcuts** [comment]
> FYI, today the doc works for both 5.x.x and 4.x.x.

Nice, I've triggered a new crawl this morning so it's already finished!

>  the documentation will be broken every now and then ?

On 10 crawls, 3 were missing a few results, so it's possible yes :/

**Comment by shortcuts** [comment]
Closing since stalled.
