### ISSUE TITLE
Docsearch stopped working, index does not exist

### ISSUE THREAD

**Issue by rlamana** [algolia/docsearch-configs#4462]
# Do you want to request a **feature** or report a **bug**?

bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= okteto

## What is the **current** behaviour?

We've been using DocSearch since 2019. Last week it stopped working with the following error output:

```
{name: "ApiError", message: "Index okteto does not exist", status: 404, transporterStackTrace: Array(1)}
```

Has our index been deleted for any reason and without previous notice?

## What is the **expected** behaviour?

It shouldn't fail and return search results.

#### What have you tried to solve it?

Make sure our index was "okteto", but that hasn't changed since 2019.

**Comment by shortcuts** [comment]
Hey, please see this same issue for the reasons: https://github.com/algolia/docsearch-configs/issues/4277#issuecomment-870001301

In your case, you should update your config to follow the [docusaurus v2 template](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L13-L45), you can copy everything from the `selectors` (included), to the `conversation_id` (excluded)

Feel free to open a PR right after!

**Comment by rlamana** [comment]
Thanks @shortcuts! I just sent the PR #4464, I hope it fixes the issue.

**Comment by shortcuts** [comment]
Looks like it works!

**Comment by rlamana** [comment]
@shortcuts It does! Thank you so much!
