### ISSUE TITLE
[tailwindcss] can we add support for browser-specific styles?

### ISSUE THREAD

**Issue by prasannamestha** [algolia/docsearch-configs#4522]
Hi,
Safari broswer hides the footer content in iPhone hence making it a requirement for us to add bottom padding only to safari browsers on iPhone. Can we accomplish the same in tailwindcss?

Relevant issue: https://stackoverflow.com/questions/31541998/ios-mobile-safari-the-bottom-bar-covers-my-footer

Thanks

**Comment by shortcuts** [comment]
Closing since wrong repository
