### ISSUE TITLE
[dydu_atria] Missing results for all my queries

### ISSUE THREAD

**Issue by itproject-dydu** [algolia/docsearch-configs#4557]
Hello, I have migrated recently from docusaurus v1 to v2
Since then, the algolia search does not show any query result

Here's my configuration : 
`algolia: {
      apiKey: '4611b0336f90fafe2cb7f80f24110e74',
      indexName: 'dydu_atria',
      // searchParameters: {
      // },
      contextualSearch: true,
    },`

Am I missing something ?
thank you for you help

**Comment by shortcuts** [comment]
Hey, you forgot to update the config: https://github.com/algolia/docsearch-configs/pull/4562/commits/cb90406c5327b36cb92bb22f734e22ac75d88551

It's now done and results should appear soon!
