### ISSUE TITLE
[near] update config to docusaurus v2

### ISSUE THREAD

**Issue by bucanero** [algolia/docsearch-configs#4632]
# Do you want to request a **feature** or report a **bug**?

Algolia's search results point to wrong/missing URLs.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `near`

## What is the **current** behaviour?

We have recently upgraded `docs.near.org` from docusaurus v1 to docusaurus v2. It seems that we missed a migration step, related to Algolia's configuration.
Now the search results point to broken/missing URLs. From the migration docs, I found out that we need to update the `near.json` config file.

## What is the **expected** behaviour?

Search results point to valid web pages.

#### What have you tried to solve it?

I reviewed Docusaurus' migration docs: https://docusaurus.io/docs/migration/manual#algolia  

### Any other feedback / questions ?

Could you help with this config file update? Thank you in advance!

**Comment by bucanero** [comment]
Following the migration example from docusaurus.io, I've submitted a PR #4634

**Comment by shortcuts** [comment]
Small change needed on the PR but otherwise https://github.com/algolia/docsearch-configs/pull/4634 will fix this issue
