### ISSUE TITLE
[near] results point to the wrong domain

### ISSUE THREAD

**Issue by bucanero** [algolia/docsearch-configs#4672]
#  report a **bug**

Bug: the search results from `near-sdk.io` are pointing to the wrong domain (`docs.near.org`)

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `near`

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

- Visit https://docs.near.org
- search for "Public Method Types"
- Result should point to https://www.near-sdk.io/contract-interface/public-methods
- but you get redirected to `https://docs.near.org/contract-interface/public-methods` instead

## What is the **expected** behaviour?

Result links from `near-sdk.io` should point to the correct domain

**Comment by shortcuts** [comment]
Hey @bucanero,

There is an open issue on Docusaurus (https://github.com/facebook/docusaurus/issues/5631) with a workaround provided by @semoal: https://github.com/facebook/docusaurus/issues/5631#issuecomment-932238707

**Comment by bucanero** [comment]
Hi @shortcuts, thanks for the help!

I'll review the workaround and try to implement a fix on our side. Cheers 👋
