### ISSUE TITLE
Update search config from docusaurus 1 to docusaurus 2 format. (index "zio")

### ISSUE THREAD

**Issue by atooni** [algolia/docsearch-configs#4678]
@s-pace, @shortcuts 

# Do you want to request a **feature** or report a **bug**?

Hi there, we have updated our website at https://zio.dev from docusaurus 1 to docusaurus 2. 

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= zio

## What is the **current** behaviour?

The indexes are not refreshed after upgrading to docusaurus 2.

## What is the **expected** behaviour?

Please convert the search config to the docusaurus 2 format, so that the index refreshing works again.

**Comment by shortcuts** [comment]
Hey, you can take basically everything from the `docusaurus-2.json` config on this repository and update yours with it! (Make sure to keep your `conversation_id` and update the URLs)
