### ISSUE TITLE
Alias for facetfilters

### ISSUE THREAD

**Issue by endiliey** [algolia/docsearch-configs#469]
# Do you want to request a **feature** or report a **bug**?
feature

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=jest

## Explanation

Jest used Docusaurus as a framework, but there is a bug on how we translate the facetfilters on the currently used Docusaurus version. (https://github.com/facebook/Docusaurus/pull/797) It will only be fixed after Docusaurus release 1.3.1 and jest upgrade their Docusaurus version to 1.3.1

When jest is currently on 'en' and version '23.0'. It will send
```
facetFilters: [ "language:en", "version:current" ]
```
instead of

```
facetFilters: [ "language:en", "version:23.0" ]
```

## Proposal

We want version alias. Example: if we send facetfilter `version:current` it will be translated to `version:23.0`

**Comment by s-pace** [comment]
👋 You can change the meta and put it as an array:

<meta name="docsearch:language"content='["23.0","latest"]'>

WDYT @endiliey ?

**Comment by endiliey** [comment]
@s-pace Can you give a specific example ?

**Comment by s-pace** [comment]
Yes I put one but it was rendered as HTML. See the edit aboce

**Comment by endiliey** [comment]
LGTM. Unfortunately I'm trying to look into an alias in the docsearch-configs itself because it's harder for user to upgrade to Docusaurus

So that when user set
`facetFilters: [ "language:en", "version:current" ]`

and maybe something like this in their config
```
facetFiltersAlias: {
  'version': {
     'current': '23.0'
  }
}
```

The previous facet filter is seen as
`facetFilters: [ "language:en", "version:23.0" ]`

WDYT?

**Comment by s-pace** [comment]
If you already know it, could it be possible to change it from the Search UI instead?

it will populate the meta tags and not the alias.

**Comment by endiliey** [comment]
Yeah, the easiest is actually to change it from the Search UI. 

It's just that if user use an older version of Docusaurus, they cannot change from the Search UI because the search UI is inside `node_modules`. 

Anyway, seems that they'll have to upgarde to fix this. I'm closing this. Thank you for your time @s-pace 😃
