### ISSUE TITLE
Bad doc link on the main readme

### ISSUE THREAD

**Issue by johnspurlock-skymethod** [algolia/docsearch-configs#4713]
The "dedicated documentation" link in the main readme of this repo is a 404.

Please check the [dedicated documentation](https://docsearch.algolia.com/docs/config-file/) to have...

**Comment by shortcuts** [comment]
Thanks! Updated in https://github.com/algolia/docsearch-configs/commit/7345d2aa0b2adfb7d01d2a55daf0c494516cb3dc
