### ISSUE TITLE
[element-en] Missing results for query "table"

### ISSUE THREAD

**Issue by kavyabaskar** [algolia/docsearch-configs#4720]
The search functionality does not seem to work on the website. The loading indicator spins forever and nothing is returned.

**Comment by shortcuts** [comment]
They are running their own instance of DocSearch, you should submit the issue on their repository: https://github.com/element-plus/element-plus

**Comment by shortcuts** [comment]
Hint: Looking at the console error, they should upgarde to the latest version of DocSearch v3: `3.0.0-alpha.40`
