### ISSUE TITLE
Results not showing on my Docusaurus website

### ISSUE THREAD

**Issue by Satish7897** [algolia/docsearch-configs#4791]

**Comment by Satish7897** [comment]
I have multiple language in docusaurus ,it is giving 404 error
https://domain.com/hi/policies/terms
where hi (hindi) is the language it give 404 then after refreshing it works.

**Comment by shortcuts** [comment]
On my side, I'm getting a 404 even after refreshing, but you should ask on the Docusaurus repository, they might have better advices: https://github.com/facebook/docusaurus

**Comment by shortcuts** [comment]
Closing since inactive
