### ISSUE TITLE
Missing results in electronjs.org

### ISSUE THREAD

**Issue by molant** [algolia/docsearch-configs#4829]
# BUG: missing results in electronjs.org

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=electronjs

## What is the **current** behaviour?

1. Navigate to https://www.electronjs.org/docs/latest
2. In the search box type `ipcRenderer`
3. No results are found even though there is an `ipcRenderer` page:

![image](https://user-images.githubusercontent.com/606594/141202010-a0209c73-dcf2-4cb9-b7a6-306e976f0bbd.png)

## What is the **expected** behaviour?

I would expect to get the results.

#### What have you tried to solve it?

- I've checked that the page exists in the [sitemap.xml](https://www.electronjs.org/sitemap.xml)
- I've looked into the [configuration](https://raw.githubusercontent.com/algolia/docsearch-configs/master/configs/electronjs.json) and do not have any `stop_url` that could be interfering
- I tried running locally the scrapper but because we are using docsearch it seems like I'm not allowed
- I thought it could be a problem with our markdown but comparing indexed and not indexed files I can't seem to find a pattern

#### Any quick clues?

First I thought that the "Renderer Process Modules" weren't indexed, but it turns out `crashReporter` is (there should be 7 in total):
![image](https://user-images.githubusercontent.com/606594/141202594-a90ca850-94f6-40d6-8dd1-1b259c3e0ed1.png)

Something similar happens with "Custom DOM Elements" where only `<webview>` is indexed (I checked the extra 180 links):

![image](https://user-images.githubusercontent.com/606594/141202757-fddbd275-d23a-4353-af86-8bc7dac4f57c.png)

Other tems like `clipboard`, `contextBridge`, `dialog`, etc. so it doesn't seem to be related to where the doc is in the sidebar.

We have our docs translated. Could we be hitting a limit on the number of pages being indexed?

/cc @erickzhao

**Comment by shortcuts** [comment]
Hey @molant, thanks for opening this issue.

> We have our docs translated. Could we be hitting a limit on the number of pages being indexed?

DocSearch indices have unlimited records/searches so it might not be that

> I would expect to get the results.

It looks like last crawl (21 hours ago) only outputted 14k records, while the few crawls I just ran locally returns + 160k records. I've pushed this small update that removes ~50% of the visited links (they all return 0 records), to make sure the task does not timeout: https://github.com/algolia/docsearch-configs/pull/4830

I'll monitor next crawls but also migrate your index to our new infra ASAP (see: https://docsearch.algolia.com/docs/migrating-from-legacy) as it offer a full transparency of the crawl output and allow you to trigger a new one on your side!

**Comment by shortcuts** [comment]
Update: new crawl finished, all of the above terms are now searchable. Will monitor next crawls to make sure it does not happen but will migrate the `electronjs` index ASAP!

**Comment by molant** [comment]
Awesome, thanks a lot @shortcuts !

Will we get notified when the index is migrated to the new infra?

**Comment by shortcuts** [comment]
> Will we get notified when the index is migrated to the new infra?

Sure, owner(s) of the current index will have an invite to their new app and a recap/migration guide email

**Comment by shortcuts** [comment]
I'm closing the issue since it seems to work :D
