### ISSUE TITLE
100% no result rate since 27th Oct for scanpy

### ISSUE THREAD

**Issue by ivirshup** [algolia/docsearch-configs#4839]
# Do you want to request a **feature** or report a **bug**?

**Bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=scanpy

## What is the **current** behaviour?

No searches get hits!

Since 27th october:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/8238804/141809361-ecc6b088-1fa1-4132-9e90-903623dd1906.png">

## What is the **expected** behaviour?

Some searches get hits!

#### What have you tried to solve it?

Not much. I saw there is a new version out and suspect that might be related. However, I can't see any release dates here.

#### Any quick clues?

* Seems like it could have something to do with the new release
* I have not received a migration email yet, so are using 2.6
* We did not make a new build around when queries stopped finding results.

**Comment by shortcuts** [comment]
Hey @ivirshup,

You can track the release process of DocSearch v3 on https://github.com/algolia/docsearch, but since you're using v2 it's not related to those releases.

Is your config still compliant with your website structure since the last update? https://github.com/algolia/docsearch-configs/blob/master/configs/scanpy.json

**Comment by shortcuts** [comment]
It also seems there's now a `docsearch` version, is there anything to do with that? https://scanpy.readthedocs.io/en/docsearch/

**Comment by ivirshup** [comment]
> Is your config still compliant with your website structure since the last update? 

I believe so. 

We did not make any updates around the time that queries started failing. We have made an update since though, (Nov. 3, 2021).

> It also seems there's now a docsearch version

Ah that was for testing, actually wasn't aware that was currently publicly visible!

**Comment by ivirshup** [comment]
Oh, thanks for the fix! Also the quick response!

What was the issue exactly?

**Comment by shortcuts** [comment]
Selectors were only working on the `docsearch` version so no records were created for the two other versions
