### ISSUE TITLE
[infracost] Missing results for query in table entries, e.g. "aws_dms_replication_instance"

### ISSUE THREAD

**Issue by alikhajeh1** [algolia/docsearch-configs#4842]
I noticed that the table entries in the following 3 pages aren't showing-up in the search results, any idea if there's something we can do to fix this? the markdown code for the pages are [here](https://github.com/infracost/docs/tree/master/docs/supported_resources).
https://www.infracost.io/docs/supported_resources/aws
https://www.infracost.io/docs/supported_resources/azure
https://www.infracost.io/docs/supported_resources/google

**Comment by shortcuts** [comment]
Hey @alikhajeh1,

Only the first and last child of the table are indexed in your config: https://github.com/algolia/docsearch-configs/blob/master/configs/infracost.json

If you'd like to update it, feel free to open a pull request

**Comment by alikhajeh1** [comment]
Thanks @shortcuts! I should have noticed that sooner 😓 I sent a [PR](https://github.com/algolia/docsearch-configs/pull/4845) just now
