### ISSUE TITLE
[cassandre] Missing results for query "a"

### ISSUE THREAD

**Issue by straumat** [algolia/docsearch-configs#4851]
I set this configuration:
```
plugins: [
        // Google analytics
        ['@vuepress/plugin-google-analytics', {'id': 'UA-158255496-1'}],
        // Docsearch
        [
            '@vuepress/plugin-docsearch',
            {
                appId: 'BH4D9OD16A',
                apiKey: '94f09cface8844077df616a30863e73a',
                indexName: 'cassandre',
                searchParameters: {
                    facetFilters: ['tags:v2'],
                }
            },
        ],
    ]
```
But there is no reply in search for: [https://trading-bot.cassandre.tech](https://trading-bot.cassandre.tech)

**Comment by shortcuts** [comment]
Hey, `searchParameters` should be removed since you don't have `tags` in your config, see [filtering your search](https://docsearch.algolia.com/docs/DocSearch-v3#filtering-your-search)

**Comment by straumat** [comment]
@shortcuts thx a lot. And i apologize to not have make more research before posting this issue

**Comment by shortcuts** [comment]
No problem, enjoy DocSearch :D
