### ISSUE TITLE
Jest search is not working

### ISSUE THREAD

**Issue by endiliey** [algolia/docsearch-configs#486]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=jest

## What is the **current** behaviour?

https://github.com/facebook/jest/issues/6640
Search is not working

## What is the **expected** behaviour?
Search is working

#### Any quick clues?
Previously it was working. When we update our docs to 23.3 it suddenly stop on working.

<img width="958" alt="result is ok" src="https://user-images.githubusercontent.com/17883920/42361929-77a897be-8123-11e8-87a8-0bf03ddd3a6e.PNG">

**Comment by endiliey** [comment]
Seems that it has finished scraping and now it works.

**Comment by s-pace** [comment]
Indeed @endiliey 

Please note that you need to update `facetFilters` from older version. It is working find on the latest one but older version page are not update:

Example:
See DocSearch's snippet for
https://jestjs.io/docs/en/22.2/getting-started.html

```
              var search = docsearch({
                
                apiKey: '833906d7486e4059359fa58823c4ef56',
                indexName: 'jest',
                inputSelector: '#search_input_react',
                algoliaOptions: {"facetFilters":["language:en","version:23.3"]}
              }); 
```

The search from these pages will looking into latest content and redirect to the latest version pages.

**Comment by endiliey** [comment]
@s-pace 
I have submitted https://github.com/facebook/jest/pull/6644 for that. Going to merge soon

![search according to version](https://user-images.githubusercontent.com/17883920/42369964-1696f022-813e-11e8-8957-7d4d8951426e.gif)

**Comment by s-pace** [comment]
Perfect thanks
