### ISSUE TITLE
Reducing turnaround on new version documentation hugely helps

### ISSUE THREAD

**Issue by jeevatkm** [algolia/docsearch-configs#488]
Hello DocSearch - I was wondering, is there quicker way to submit new version config? So that DocSearch engine could crawl and index new version docs. 

Reducing turnaround on new version documentation hugely helps, because _latest version search yields Zero results_. 

Current configuration process taking more turnaround time #487. 

**Proposed Process:**

* Docsearch config kept at root directory of the documentation website. For eg.: `https://docs.aahframework.org/docsearch.json`
* User update the configuration for new release
* DocSearch crawler reads the configuration from root directory of the website and does the indexing on specified interval
* Alternate: if user needs it urgent, they could login to DocSearch dashboard and trigger re-index or refresh index
   - Calling an API also an option to trigger the process

**Please note: DocSearch does so much to open source projects, Kindly take this issue as improving DocSearch platform.**

**Comment by s-pace** [comment]
👋 @jeevatkm 

Thank you for your ideas

Solved thanks to https://github.com/algolia/docsearch-configs/commit/b5a612d26cc3a2ff88b2934926e4993381cf3e2a

Information available #487

**Comment by jeevatkm** [comment]
@s-pace You have wonderfully handled, new documentation version gets automatically indexed.
