### ISSUE TITLE
[edgemesh] Missing results for query "getting started"

### ISSUE THREAD

**Issue by Poorunga** [algolia/docsearch-configs#4892]
My website is https://edgemesh.netlify.app/, and algoloa docsearch cannot take effect. However, algolia docsearch is available in codesandbox: https://rq4h2.csb.app/

I use vuepress to build my website. This is the configuration of my config.ts:
```
  plugins: [
    [
      '@vuepress/plugin-docsearch',
      {
        appId: 'YD2E315IKY',
        apiKey: '0267453c2facee5d3ab2add0ad6a9be8',
        indexName: 'edgemesh',
        searchParameters: {
          facetFilters: ['tags:v2'],
        },
        locales: {
          '/zh/': {
            placeholder: '搜索文档',
          },
        },
      },
    ],
  ],
```

**Comment by shortcuts** [comment]
Hey

Looking at the snippet you shared, I'd assume that `tags` is either not defined in your DocSearch config or in the `attributesForFaceting.customSettings`

Is the config you used to crawl your website [this one](https://github.com/algolia/docsearch-configs/blob/master/configs/edgemesh.json)?

**Comment by Poorunga** [comment]
@shortcuts Yes, thank you for your reply.

**Comment by Poorunga** [comment]
I removed the tags and everything is ok
