### ISSUE TITLE
[avax] Missing results for query "avax"

### ISSUE THREAD

**Issue by yulin-dong** [algolia/docsearch-configs#4893]
No search result for query of anything such as `avax` on https://docs-beta.avax.network/. Your help is greatly appreciated.

**Comment by shortcuts** [comment]
Hey,

To use the `contextualSearch` option of Docusaurus, your DocSearch config needs to follow the Docusaurus v2 config template, you can read more here: https://docusaurus.io/docs/2.0.0-beta.8/search#contextual-search
