### ISSUE TITLE
Updated doc structure in Fastify and the indexing should be updated

### ISSUE THREAD

**Issue by mcollina** [algolia/docsearch-configs#4947]
We have changed the structure for the Fastify documentation and now the search is not reporting the correct link anymore.

Basically `https://www.fastify.io/docs/latest/Reply/#reply` became `https://www.fastify.io/docs/latest/Reference/Reply/#reply`

How do we need to update https://github.com/algolia/docsearch-configs/blob/master/configs/fastify.json?

Or maybe we should just wait?

**Comment by shortcuts** [comment]
Hey

`Fastify` index have been migrated to [our new infra](https://docsearch.algolia.com/docs/migrating-from-legacy), you/your team members should have receive an email with an invite to join their app and a few details regarding your credentials.

You will be able to edit the config from our web interface and start a crawl directly!

**Comment by mcollina** [comment]
Thanks, it all worked fine!
