### ISSUE TITLE
Search hits are not categorized

### ISSUE THREAD

**Issue by davidcetinkaya** [algolia/docsearch-configs#4955]
# Do you want to request a **feature** or report a **bug**?
Hi Algoila!
I want to request a feature I guess. But I think what I want to achieve is already possible. I just don't know **how** to do it.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= embla-carousel

## What is the **current** behaviour?

All search hits are categorized under **Documentation**, no matter what page the hits belong to.

<img width="1124" alt="search results" src="https://user-images.githubusercontent.com/11529148/146385171-a47a4d9b-7177-4877-acca-66135bb0a603.png">

<img width="1231" alt="parent page" src="https://user-images.githubusercontent.com/11529148/146386781-aefccae9-b417-4a78-a7bc-f10041197314.png">

## What is the **expected** behaviour?

A search hit that's on the following page `<site-url>/api/options` should be categorized under API, just like it works on [your website](https://docsearch.algolia.com/):

<img width="1407" alt="algolia search" src="https://user-images.githubusercontent.com/11529148/146386335-a0e3c5be-6f2d-408f-81a4-fc2d94061255.png">

#### What have you tried to solve it?
I've skimmed through your documentation but I didn't manage to find how to solve this.

#### Any quick clues?

😕 

### Any other feedback / questions ?

Not at the time of writing.

Thank you in advance!

Best,
David

**Comment by shortcuts** [comment]
Hey, the group title you see here is the result of the `lvl0` value. Looking at your config, it's an empty selector that fallbacks to the `defaultValue`.

You can update the `lvl0.selectors` field to match a DOM element you'd like to retrieve, and keep the fallback value in case it's not found!

**Comment by davidcetinkaya** [comment]
Hello @shortcuts,

Thank you for your swift response and pointing me in the right direction. I've added the `algolia-docsearch-lvl-0` class name to all the parent pages and for some reason it's combining all the `lvl0` pages into a single category:

### Class name (selector):

<img width="1431" alt="class name" src="https://user-images.githubusercontent.com/11529148/146457398-c43c0fcb-fd44-4946-9682-81198dd750c9.png">

### Crawler config and URL Tester:
<img width="1308" alt="config-results" src="https://user-images.githubusercontent.com/11529148/146457451-e939d7d3-d67d-456d-91a4-2266ad8b35b1.png">

### Search hits on website
<img width="1107" alt="results" src="https://user-images.githubusercontent.com/11529148/146458016-e0aeedb0-9af0-426b-8312-a46b7ceca9a4.png">

I'm probably missing something obvious here so what am I doing wrong? For example, I want the `React` page to be listed under the `Get Started` category when a visitor types `react`.

Best,
David

**Comment by shortcuts** [comment]
I assume the reason is that it's applied to every parent sidenav title, while it should be only on the `active` link, you can try your selector in the console with `document.querySelectorAll()` which will reflect how behaves our crawler

**Comment by davidcetinkaya** [comment]
@shortcuts ah I see. Thank you very much for your swift response. That helped and things are now working as expected.

Cheers,
David
