### ISSUE TITLE
Scalafix algolia index does not exist anymore

### ISSUE THREAD

**Issue by mlachkar** [algolia/docsearch-configs#5025]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=scalafix

## What is the **current** behaviour?
The actual error is: 
`Index scalafix does not exist`

### Any other feedback / questions ?
I know that emails have been sent to do a migration, but I don't know who received the email for scalafix, so I m not able to do the migration. thanks

**Comment by shortcuts** [comment]
Hey, `scalafix` have not been migrated yet

**Comment by mlachkar** [comment]
I know, but I can't find who the email has been sent to. I m the new maintainer and I would like to process with this migration.

**Comment by shortcuts** [comment]
The email we have is @olafurpg's, also, any team member currently added to the `scalafix` will receive the email

**Comment by mlachkar** [comment]
I have talked to @olafurpg, and he received only the `scalameta` index. How can we add someone to the team ? Is it the github team?

**Comment by shortcuts** [comment]
> I have talked to @olafurpg, and he received only the scalameta index.

This is indeed because only `scalameta` have been migrated yet, migration take place in batches where indices are randomly selected. We're at +50% of the migration atm (~2k/~4k), so `scalafix` turn should come soon! :D

> How can we add someone to the team ?

You can contact support@algolia.com with your appId, indexName and email address to ask to be added to the team. (After the migration, you will be able to add team members yourself)

**Comment by mlachkar** [comment]
Thank you so much! I understand better. 
So meanwhile I guess it's normal that the index of scalafix is not working (I think it stopped working around the 20th December) ?

**Comment by shortcuts** [comment]
> So meanwhile I guess it's normal that the index of scalafix is not working (I think it stopped working around the 20th December) ?

Indices on the legacy infra should still work 🤔  I'm taking a look

**Comment by shortcuts** [comment]
Fixed in https://github.com/algolia/docsearch-configs/pull/5026

**Comment by mlachkar** [comment]
Thank you so much for your quick and effective help !!
