### ISSUE TITLE
[Help]: can't add midwayjs.org domain in crawl..

### ISSUE THREAD

**Issue by czy88840616** [algolia/docsearch-configs#5033]
#5020

I received an email before migrating to doc search v3. Recently, midwayjs.org has just updated a new version. I went to check DocSearch today. It may have been deleted by mistake. Now it is not available at https://crawler.algolia.com/ and When I edit https://www.algolia.com/, I can't add a new domain name under my own application, and it will prompt that I have no permission.

I got an error message  "You don't have the permissions to execute this action. Contact the owner of the Application or the support if you believe it's a mistake.“

I don't know what to do, can you help me?

@shortcuts 

![image](https://user-images.githubusercontent.com/418820/149621143-44b59c32-a7db-40e5-b94e-a74808135ae9.png)

**Comment by shortcuts** [comment]
Hey, as we have two apps for midwayjs, I'll delete the `midwayjs` as `midway` is the one used on the prod app. I've added `https://midwayjs.org/` to the domains of `midway` so you can use it properly!

DocSearch users are not allowed to add domain without making a support request, I'll update the error message with a description to make it more explicit!
