### ISSUE TITLE
No new updates on index after updating to @docsearch/react

### ISSUE THREAD

**Issue by acelaya** [algolia/docsearch-configs#5071]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=shlink

## What is the **current** behaviour?

I received an email later last year saying I had to update to `@docsearch/react`, and that I had to request new API key and app ID, which I did.

Now, I have done some changes to the page and I have noticed the index does not include them. I'm not completely sure if the reason is the update to `@docsearch/react`, or it just happenes to be at more or less the same time.

## What is the **expected** behaviour?

The new information and new pages appear in search.

**Comment by shortcuts** [comment]
Hey, you can take a look at the config being indexed for this website by logging in to https://crawler.algolia.com/. This is most likely an indexing issue

**Comment by acelaya** [comment]
Thanks!

Let me take a look.

**Comment by acelaya** [comment]
Ok, I have checked and it says it will run the crawling today, in 6h.

Last one was last Friday, according to the page. I was almost sure there was an indexing every day, not every week, and that's why I was confused not to see the contents after 2 days.

I'll close this for now. Thanks!

**Comment by shortcuts** [comment]
It was previously, but we now offer the possibility to trigger crawls manually (overview -> restart crawling), so we moved the schedule to once a week!

**Comment by acelaya** [comment]
Totally makes sense
