### ISSUE TITLE
Duplicate search results for URLs with/without `.html` pointing to same resource

### ISSUE THREAD

**Issue by j-low** [algolia/docsearch-configs#510]
# Do you want to request a **feature** or report a **bug**?
Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= cockroachlabs

## What is the **current** behaviour?
Showing duplicate results with and without `.html` appended to URL.  This did not seem to be occurring until recently.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
Executing a search for most terms will reproduce the bug seen in screenshot.

![urls](https://user-images.githubusercontent.com/6320333/43413262-9afc6082-93fd-11e8-9fab-26e737339ff4.png)

## What is the **expected** behaviour?
Single result should be returned for a given page (i.e. the URL with `.html` appended).

#### What have you tried to solve it?
Looking through config history for recent changes that may have impacted indexing; nothing appeared likely-- only recent change was to add new docs version to config.

**Comment by s-pace** [comment]
👋 
Please update your sitemap without any .html
