### ISSUE TITLE
tags aren't added to records

### ISSUE THREAD

**Issue by mojavelinux** [algolia/docsearch-configs#515]
My attempt to add tags to search records has been fruitless. Here's the configuration I'm using:

```
  "start_urls": [
    {
      "url": "https://docs.example.com/product-a/(?P<version>.*?)/",
      "variables": {
        "version": ["5.1", "5.5"]
      },
      "tags": ["product-a"]
    }
  ]
  ...
  "custom_settings": {
    "attributesToRetrieve": [
      "anchor",
      "hierarchy",
      "tags",
      "url"
    ]
  }
```

Am I missing something in order for tags to be recorded? (I'm using the provided Docker container to run the scraper).

**Comment by s-pace** [comment]
👋 @mojavelinux 

Small misleading point here.
You want to use [searchable attribute](https://www.algolia.com/doc/guides/ranking/searchable-attributes/#searchable-attributes-overview) which define attributes you want to search on instead of [attributesToRetrieve](https://www.algolia.com/doc/api-reference/api-parameters/attributesToRetrieve/) that define the attribute to send you for every records.

**Comment by s-pace** [comment]
What do you mean?

`custom_settings` expose you the algolia settings straight away. You only need to use the proper attribute.

**Comment by mojavelinux** [comment]
I don't see any additional information in the index when I look at it in the Algolia web interface (the Indices scree). So my question is, how to I inject information other than what is provided by the selectors? There doesn't seem to be a way to do it.

**Comment by mojavelinux** [comment]
Here's what I see:

![image](https://user-images.githubusercontent.com/79351/43452485-cd3aae92-9474-11e8-9982-c231da06d51d.png)

**Comment by s-pace** [comment]
Ah you mean add information not coming from your pages? This is not possible so far

**Comment by mojavelinux** [comment]
Then I'm confused why so many different sites are configuring tags and custom attributes, like gitlab for example.

https://github.com/algolia/docsearch-configs/blob/master/configs/gitlab.json#L3-L13

Is that just pointless metadata? I really feel like I'm missing something about this configuration.

**Comment by mojavelinux** [comment]
And what if I have a tag in the page itself? How do I extract it and put it somewhere that can be faceted? For example, I have the following metadata in the HTML head:

```
<meta name="dcterms.subject" content="server">
<meta name="dcterms.identifier" content="5.5">
```

I really need to be able to focus the search by a specific subject / tag / component.

**Comment by mojavelinux** [comment]
Any advice? I'd love to better understand this tags feature because it really looks like the solution I need for faceting. In the meantime, I'm going to start diving into the code to see if I can understand what's going on in the crawler.

**Comment by s-pace** [comment]
Using meta data is the recommended way.
<meta name="docsearch:subject" content="server">
<meta name="dcterms:version" content="5.5">

We are scraping it automatically. You will only need to add it as an attributeForFacetiing but please ping me asap. I will do it for you

**Comment by mojavelinux** [comment]
Thanks for the tip! I'll give that a try and report back.

**Comment by mojavelinux** [comment]
Yep, adding this to the end of the config worked.

```
"attributesForFaceting": ["tags"]
```

Thanks again for the tip, @s-pace! I now consider this issue resolved.

**Comment by mojavelinux** [comment]
To clarify, that's located in this place in the config:

```
{
  ...
  "custom_settings": {
    "attributesForFaceting": ["tags"]
  }
}
```

However, I see that tags were already included by default if I didn't specify. Therefore, I think the problem may have been that there was a restriction on my account. When I upgraded my account, all of a sudden tags started getting adding (as well as other variables).
