### ISSUE TITLE
[cockroachlabs] missing search result for alpha feature

### ISSUE THREAD

**Issue by j-low** [algolia/docsearch-configs#556]
# Do you want to request a **feature** or report a **bug**?
Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=cockroachlabs

## What is the **current** behaviour?
"encryption at rest" fails to return `https://www.cockroachlabs.com/docs/v2.1/encryption.html` result (which contains "Encryption at Rest" in `<h1>` document title)

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
`https://www.cockroachlabs.com/docs/v2.1/encryption.html` URL should be top result

#### What have you tried to solve it?
Checked sitemap to ensure URL is listed; checked config for typos

**Comment by s-pace** [comment]
👋 @j-low 

Thank you for sharing and explaining your whole process.

I have checked [your sitemap](https://www.cockroachlabs.com/sitemap.xml) and I couldn't find any URLs matching your `start_urls` from it. Please update your sitemap and add it as a `sitemap_urls`.

We only crawl your website so far (following every hyperlinks). I can confirm you that after https://github.com/algolia/docsearch-configs/commit/849700142316ebecfa142b22fd4d3c16b86ff9ae, https://www.cockroachlabs.com/docs/v2.1/encryption.html is crawled.

**Comment by j-low** [comment]
@s-pace thanks for checking that out.  That sitemap looks out-of-date w/r/t what I see in my local version of our docs repo.  That seems like it's the source of the issue.  I'll figure out what's going on and make the updates.
