### ISSUE TITLE
Please crawl more pages for nim-lang

### ISSUE THREAD

**Issue by Araq** [algolia/docsearch-configs#56]
I love you for supporting nim-lang, but after trying the search I have to say: it's still not something that we can put on our website since the search results are too poor. For example, searching for 'split' doesn't contain a search result like http://nim-lang.org/docs/strutils.html#split,string,set[char],int

So lib.html is crawled, but none of actual Nim's stdlib. I would create a PR if only I knew how to do it.

**Comment by ElPicador** [comment]
Hi Araq, 

By default, we do not crawl source code. I'll add it to your configuration.
For the doc, you can find it here: https://github.com/algolia/docsearch-configs#docsearch-configurations.
And your configuration is here: https://github.com/algolia/docsearch-configs/blob/master/nim-lang.json

**Comment by ElPicador** [comment]
I've updated your configuration: 

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'a803bc5bd523a7ae3ae6a6fd80179cd3',
  indexName: 'nim-lang',
  inputSelector: '### REPLACE ME ####'
  algoliaOptions: { 'facetFilters': ["tags:$TAGS"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Replace $TAGS with the tags you want to search on.
   The list of possible tags is harcoded in the config.
   So as of today you have: backends, filters, gc, intern, lib, manual, nep1, nimc, nims, stdlib, tools
