### ISSUE TITLE
How to configure for <code> block

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch-configs#57]
I am having a hard time figuring out what I need to configure so the scrapper can index the ```<code>``` block on my site. 

This site is uses the same template as me, how would I index the code listed in it: https://myclabs.github.io/jquery.confirm/

**Comment by maxiloc** [comment]
You can hava a look at https://github.com/algolia/docsearch-configs/blob/da321ce83bc65e51b96f4bed891f84e71d904632/configs/bolt.json,

**Comment by maxiloc** [comment]
Usually we do not recommend it as it creates a lot of noise in the search result.
