### ISSUE TITLE
carbondesignsystem.json

### ISSUE THREAD

**Issue by alisonjoseph** [algolia/docsearch-configs#666]
Hi 👋 I'm a developer working on the carbon design system website and was wondering if you had any suggestions for updating our config to avoid duplicate results. We currently have a redirect in place on many of our pages that is causing this. For example, if you search for "button" you get 

http://www.carbondesignsystem.com/components/button/code/#skip-to-content
and
http://www.carbondesignsystem.com/components/button/#skip-to-content

(the bottom link redirects to the /code link)

Was also wondering why it would link to the skip to content link on the page and wondering if there was a way to control the order search results returned? (for example why is experimental second?)

<img width="500" alt="screen shot 2018-12-10 at 7 45 03 am" src="https://user-images.githubusercontent.com/2753488/49736377-98255700-fc4f-11e8-8178-fcee5fe61a24.png">

One more question, we are also launching http://next.carbondesignsystem.com today and was wondering if we could also get a search set up for that site? 

Thank you! 🙌

**Comment by alisonjoseph** [comment]
Hi, it seems that our page titles aren't being indexed. Searching "tooltip" for instance returns nothing, even though we have a page with that name, and ` "lvl1": "h1#page-title",` is in our [config file](https://github.com/algolia/docsearch-configs/blob/master/configs/carbondesignsystem.json). 

https://www.carbondesignsystem.com/components/tooltip/code

Any help would be greatly appreciated! Thank you 😄

**Comment by alisonjoseph** [comment]
Hey @s-pace I applied for http://next.carbondesignsystem.com a couple weeks ago and haven't heard back, how long does it usually take? Thanks! 😄

**Comment by s-pace** [comment]
Hey @alisonjoseph, sorry for the delay, I have provided it to you by email.

**Comment by s-pace** [comment]
As for this issue, I have checked it on your website and it seems that this data is correctly indexed:
![image](https://user-images.githubusercontent.com/32097720/52853435-eb1dfd80-311b-11e9-8502-707dcf8c497d.png)

Closing it for now, feel free to re-open it if needed :)

**Comment by alisonjoseph** [comment]
thanks 🎉
