### ISSUE TITLE
Docsearch is not working for any site pages

### ISSUE THREAD

**Issue by MaximKudriavtsev** [algolia/docsearch-configs#679]
# Do you want to request a **feature** or report a **bug**?

Bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `devextreme_reactive`

## What is the **current** behaviour?

We are using Algolia Docsearch as search in the documentation on our project.
Our documentation page has 2 parts:
- Guides
- API Reference

When you are staying in a Guides part the Docsearch is working fine, but if you are staying in an API Reference part the Docsearch are not working.

In this case, we founded a console error `Uncaught TypeError: docsearch is not a function`.

To reproduce
- visit the Guides part https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/
- try to search (all works fine)
- visit an API Reference part https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/
- try to search (search are not working and console error)

This behavior is observed only in our [Grid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/) product pages.
If you visit the [Chart](https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/getting-started/) product pages (with the same page code), all works fine.

## What is the **expected** behaviour?

Docseacth will work fine in the Grid product page as it works in other our product pages.
See and try
- [Chart](https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/getting-started/)
- [Core](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/)

#### What have you tried to solve it?

We tried to change the `input` `id` to another one, the console error was changed `Uncaught TypeError: docsearch is not defined`.

#### Any quick clues?

None

### Any other feedback / questions ?

Also, how will we chage the our account email address?

Thanks in advance for your consideration!

**Comment by s-pace** [comment]
👋 @MaximKudriavtsev 

In order to change owner, please send an email at docsearch@algolia.com 

I think the issue from the reference page comes from the fact that the JS asset is delivered after you run the code.

Could you use this snippet instead?
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js" onload="docsearch({apiKey: '4cd7a76d4bc286ae69fe26182a8d4b18',
    indexName: 'devextreme_reactive',
    inputSelector: '#docsearch',
    algoliaOptions: { 'facetFilters': ["techno:react", "tool:grid"] },
    debug: false
})" async></script>
```

**Comment by MaximKudriavtsev** [comment]
👏 @s-pace 

Thank you very much for the response! Your snippet resolved my problem.
