### ISSUE TITLE
[dgraph] Duplicate search results (pages with trailing slash)

### ISSUE THREAD

**Issue by danielmai** [algolia/docsearch-configs#744]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=dgraph

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

When searching in https://docs.dgraph.io, many pages return duplicate results, e.g., searching for "dgraph" returns these two links:

- `https://docs.dgraph.io/get-started#dgraph`
- `https://docs.dgraph.io/get-started/#dgraph`

![2019-02-25-140006_3440x1440_scrot](https://user-images.githubusercontent.com/2251820/53371694-ce48ad80-3905-11e9-936b-1cdc5097904e.png)

## What is the **expected** behaviour?

Only a single result is returned (ideally the link without the trailing slash.

#### Any quick clues?
I read the ["duplicate results" FAQ](https://community.algolia.com/docsearch/faq.html#why-do-i-have-duplicate-content-in-my-results%3F) and it looks like it requires a change to the dgraph.json config in this repo.

**Comment by s-pace** [comment]
👋 @danielmai 

You needed to PR a configuration in order to fix this issue. It has been solved [by this commit](https://github.com/algolia/docsearch-configs/commit/6f6c5c26f678f6d0f189d5eeb7652ff023e097de) 

Please note that adding a redirection status `3XX` on one of the URL would have also fixed this issue.

**Comment by danielmai** [comment]
Thanks for fixing our config, @s-pace. Cheers!

Thanks for the tip about the 3XX behavior.
