### ISSUE TITLE
Search stopped working

### ISSUE THREAD

**Issue by alisonjoseph** [algolia/docsearch-configs#756]
The search on https://www.carbondesignsystem.com/ stopped working for most search terms recently. We haven't changed anything major on the site. Any ideas? (search for "button" for example)

**Comment by s-pace** [comment]
👋 @alisonjoseph,

This issues is due to the old way of client side emulation we were using. It is still used from our daily crawl. I will move your index into this new way of rendering. It should fix your recurrent struggle.

**Comment by alisonjoseph** [comment]
🎉 thanks for the help and quick response! 🙌
