### ISSUE TITLE
CSS in search results for gatsbyjs.org

### ISSUE THREAD

**Issue by fk** [algolia/docsearch-configs#772]
👋 Hey folks! We noticed today that some results for https://www.gatsbyjs.org/ contain CSS, which unfortunately seems to have made its way into the search index.

Here's a screenshot (from localhost, with `debug: true` — produces the same result on https://www.gatsbyjs.org/) showing what is coming back when entering `sop` as query:

![image](https://user-images.githubusercontent.com/21834/54286771-c2ffae00-45a4-11e9-92b6-8477a6d83b2d.png)

The problem can also be reproduced entering almost any single character, or typing out `install`, … most probably a lot more.

The CSS picked up in the index — `css-1e9kxo{border-bottom:1px solid #e0d6eb;-webkit-transition:all 100ms cubic-bezier(0.4,0,0.2,1);transition:all 100ms cubic-bezier(0.4,0,0.2,1);}.css-1e9kxo:hover` — is contained in an inline `<style>`: https://gist.github.com/pieh/d4e59309031cdd7815023879295bae2f#file-sop-html-L47 — here's the relevant bit:

```html
<h4 class="css-10d0nsh"><style data-emotion-css="1e9kxo">.css-1e9kxo{border-bottom:1px solid #e0d6eb;-webkit-transition:all 100ms cubic-bezier(0.4,0,0.2,1);transition:all 100ms cubic-bezier(0.4,0,0.2,1);}.css-1e9kxo:hover{background:#e0d6eb;}</style><span class="css-1e9kxo">Shannon Soper</span></h4>
```

Is there an easy way to exclude those inline `<style>`s from the index via the configuration?

/cc @s-pace @pieh

**Comment by s-pace** [comment]
Thank you for the details issue and the complete explanation @fk.

Solved by using [`selectors_exclude`](https://community.algolia.com/docsearch/config-file.html#selectors_exclude-optional) from the DocSearch configuration.

**Comment by fk** [comment]
Whooaa that was fast! 🎉
Thank you so much Sylvain! 🙏🙏🙏 🤗 

(also for pointing me to the `config-file` docs — I will def. need and will do my homework there, planning on cleaning up a few selectors! — but please know that I wasn't trying to be ignorant when opening this issue)

**Comment by s-pace** [comment]
Sure no problem @fk, happy to help. Feel free to share any great detailed issue like this :)

**Comment by s-pace** [comment]
By the way @fk, I have closed [this PR ](https://github.com/algolia/docsearch-configs/pull/603) on your configuration since we had no update from your side. You might want to enable the search for v1/current version. Feel free to reopen it if needed.
