### ISSUE TITLE
www.carbondesignsystem.com

### ISSUE THREAD

**Issue by alisonjoseph** [algolia/docsearch-configs#807]
We recently pushed a new version of our website live on Monday, but as of today, we are still seeing pages from the old site in search results. Is there something else we need to do to get it to crawl the new site data?

**Comment by s-pace** [comment]
👋 @alisonjoseph 

We are currently [deploying the new release](https://github.com/algolia/docsearch-scraper/releases/tag/v1.2.0) of our crawler using chrome 73. This version is required to properly crawl your website. It is a WIP.

Anyway, I have run a new crawl of your website and your search should now works on the newest content released.

**Comment by alisonjoseph** [comment]
Thanks as always for the super quick reply! 🎉
