### ISSUE TITLE
Arrow-kt.io API docs results inclusion

### ISSUE THREAD

**Issue by calvellido** [algolia/docsearch-configs#824]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=arrow

## What is the **current** behaviour?

In [arrow-kt.io/docs](https://arrow-kt.io/docs), a section of the documentation is not shown in the results provided by the Algolia docsearch project.

## What is the **expected** behaviour?

As expressed in https://github.com/arrow-kt/arrow/issues/1415, we would like the API docs to be included as part of the results provided by the Algolia docsearch project.

### Any other feedback / questions ?

The API docs indexing seems to be explicitly removed as part of https://github.com/algolia/docsearch-configs/commit/e38b0dbb5f9993ed12e29d680f3329a4447e9b69.

So, before submitting any PR or asking for config changes, I guess it would be good to ask the reason on that exclusion. Are API documentation not advised to be crawled through Algolia?  Anything we could do on our end to have those properly included?

Thank you very much.

**Comment by s-pace** [comment]
Should be fixed, let me know wht do you think about the search
