### ISSUE TITLE
Issue with hierarchy config?

### ISSUE THREAD

**Issue by kaelig** [algolia/docsearch-configs#83]
1. Go to https://www.lightningdesignsystem.com
2. Search for "tiles"

Expected: first results include a reference to https://www.lightningdesignsystem.com/components/tiles/ 

### Actual

![screenshot 2016-10-13 11 37 03](https://cloud.githubusercontent.com/assets/85783/19361926/65853078-9139-11e6-966e-99c438f57603.png)

### Expected

![screenshot 2016-10-13 11 36 56](https://cloud.githubusercontent.com/assets/85783/19361933/6879755a-9139-11e6-9c63-c0c7cbc07631.png)

Do you know why the actual "Tiles" component doesn't rank higher than other components, considering the h1 of the component page says "Tiles"?

**Comment by maxiloc** [comment]
That is because of min_indexed_level which is set to 2, I changed it to 1. I will show you `Components > tiles` but not `Components > tiles > Base`. If it still does not work for you we can change the attributesToIndex list to arrive to the result you want.

**Comment by kaelig** [comment]
Thanks a lot! We'll go with that for now and see how this goes :)
