### ISSUE TITLE
No search results  for akeneo 3.1

### ISSUE THREAD

**Issue by mmetayer** [algolia/docsearch-configs#836]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= akeneo

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

There are no search results for the 3.1 version of docs.akeneo.com (`facetFilters: ["version:3.1"]`)

#### Any quick clues?

#835 was submitted (and merged) a day before the 3.1 version of the docs was effectively online, so it may be an indexing issue

**Comment by s-pace** [comment]
We needed to update your index. The crawl needed a small fix. Everything is alright now.

**Comment by mmetayer** [comment]
Thank you very much Sylvain!
