### ISSUE TITLE
Issue with indexing in kyma-project.io

### ISSUE THREAD

**Issue by magicmatatjahu** [algolia/docsearch-configs#895]
# Do you want to request a **feature** or report a **bug**?

I want to report **bug**.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=kyma-project

## What is the **current** behaviour?

Few days ago I created PR with regex with version in our docs for crawling [PR](https://github.com/algolia/docsearch-configs/commit/edb899f622e919bab4f8f2d77a79d9a70be46578). After merged, the indexing for all versions worked very well, but in the next day any index is not working to this time. At the moment we only can search without `faceFilters` and this is very strange, because it looks like the docSearch is indexing old content with configuration without a versions.

Our logic for changing version works like: if user is in any path in our website without prefix `docs/{version}` then docSearch is connected to `latest` version. Otherwise docSearch is connected to appropriate version, eg: `docs/master` -> master version.

Check our code for algolia - [here](https://github.com/kyma-project/website/blob/master/src/components/layout/Search/Search.tsx#L83).

## What is the **expected** behaviour?

Working indexes for all version of our docs - from 0.4 to 1.2, master and latest.

#### What have you tried to solve it?

We have tried change `way` of indexing. Firstly we had metadata in `head` tag for version - [here](https://github.com/kyma-project/website/blob/ba84c4a5b298fe6b9006864c015a87e4b33e5ef2/src/components/layout/SiteMetadata.tsx#L44) but we had this same problem which is described above. Then we decided to change configuration in this repo and we have this same issue.

#### Any quick clues?

DocSearch probably indexes content with old configuration.

### Any other feedback / questions ?

@s-pace  Can you check our problem? We will, as a kyma-project team, very grateful for help.

**Comment by s-pace** [comment]
Should be fixed. Can you confirm @magicmatatjahu ?

**Comment by derberg** [comment]
@s-pace I can confirm it works, thanks
