### ISSUE TITLE
A 404 page link shows in the search result

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#944]
# Do you want to request a **feature** or report a **bug**?

report a bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap.com

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Step 1. Go to https://pingcap.com/en

Step 2. Search `Haproxy` in the search at the top navigation

Step 3. Scroll down to `Deploy TiDB in Kubernetes on Your Laptop ` section, the links show there direct users to a 404 page (https://pingcap.com/docs/tidb-in-kubernetes/local-dind-tutorial/#access-the-database-and-monitor-dashboards). Like the screenshots:

![image1](https://user-images.githubusercontent.com/34967660/62039400-363f4f00-b22a-11e9-9bf1-c465516e6b4b.png)
![image2](https://user-images.githubusercontent.com/34967660/62039409-3a6b6c80-b22a-11e9-8c49-66d65178bad9.png)

## What is the **expected** behaviour?

The links of 404 page should not be showed in the search result.

#### What have you tried to solve it?

I searched the 404 link (https://pingcap.com/docs/tidb-in-kubernetes/local-dind-tutorial/) in the submitted [sitemap](https://pingcap.com/sitemap.xml),  and didn't find the link in the sitemap.

#### Any quick clues?

The 404 link was in sitemap, but we update the docs structure, so the URL also has been changed. Algolia might crawl the urls from the cache.

### Any other feedback / questions ?
How often algolia bot crawls the URLs from a updated sitemap?

@s-pace PTAL, thanks

**Comment by s-pace** [comment]
Will be fixed at the next crawl. Closing in the meantime. Feel free to reopen of needes
