### ISSUE TITLE
Cannot get text in lvl0 selector

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#947]
# Do you want to request a **feature** or report a **bug**?

Report a **bug**
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap.com

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Step 1. Go to https://pingcap.com/docs
Step 2. Search an item "ansible" in the search box at the top navigation
Step 3. The lvl0 of the result should be the value in the selector, like `v3.0`, `dev` or `v2.0`, but it also shows the default value `Documentatioin`

![image](https://user-images.githubusercontent.com/34967660/62183672-9dc1df80-b38d-11e9-9190-364e184d08ca.png)

## What is the **expected** behaviour?

We config the lvl0 of selectors as `button#dropdownMenuButton`, which is the selector of version switcher at the right top of docs pages, so the lvl0 of the result should be the value in the selector, like `v3.0`, `dev` or `v2.0`

#### What have you tried to solve it?
No

#### Any quick clues?
No

### Any other feedback / questions ?
Is the config correct here? Or do you have any recommendation to implement this result feature. 

![image](https://user-images.githubusercontent.com/34967660/62183932-a666e580-b38e-11e9-9708-58bde6b22990.png)

![image](https://user-images.githubusercontent.com/34967660/62188141-1b8de700-b39e-11e9-970b-4dd4bbf4d058.png)

@s-pace PTAL, thanks!

**Comment by s-pace** [comment]
Can you just use the ID? Is this ID set bu JavaScript?

**Comment by YiniXu9506** [comment]
The ID is set on the dom element. I can try just use the ID.

**Comment by YiniXu9506** [comment]
Hi @s-pace, I saw you merged the PR, but it seems the result is not what we expected. Would you please take a look again? Thanks.

**Comment by s-pace** [comment]
The PR is not deployed yet. Can you make sure this ID is rendered on the server side pls?

**Comment by YiniXu9506** [comment]
Our website is static, so I am sure we have this ID on the pages' URLs start with "https://pingcap.com/docs-cn" and "https://pingcap.com/docs".  Is the PR deployed? I check a few mins ago, it still does not work.

**Comment by s-pace** [comment]
Should be solved within 24h. Daily crawls were failing but I have solved it.

Cheers

**Comment by s-pace** [comment]
Please reopen if it is not solved within 24h

**Comment by YiniXu9506** [comment]
Awesome. Thanks!
