### ISSUE TITLE
Update the crawled pages cache

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#954]
# Do you want to request a **feature** or report a **bug**?
Report a **bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
There are many items in the return results are outdated. Users have a bad experience when they click the 404 pages. 

1. Go to https://pingcap.com/docs
2. search item 'haproxy', there is a 404 link, which is not in our sitemap. 

![image](https://user-images.githubusercontent.com/34967660/62443423-67b99c80-b78d-11e9-98bd-1c18954e85d8.png)

## What is the **expected** behaviour?
All 404 pages should not be returned to users.

### Any other feedback / questions ?
The 404 page has been updated for two weeks. Why Algolia cannot update the cache automatically, I have been reported this issue https://github.com/algolia/docsearch-configs/issues/944 last week, but it seems that you haven't resolve it. Would you please update the pingcap crawled pages manually? I would appreciate your help. Thanks!

@s-pace

**Comment by s-pace** [comment]
Thanks for sharing. I will solve it when I am back on a computer. In less than 3 weeks. The crawl must be failing.

**Comment by s-pace** [comment]
Crawl was failing indeed. It was impacted by a wrong JSON. Should be fixed thanks to https://github.com/algolia/docsearch-configs/commit/09eaaefe6d9b2a84ab1bc0ecd221de02282fe7bf

**Comment by s-pace** [comment]
Please reopen if it is not solved tomorrow EOD

**Comment by s-pace** [comment]
I have triggered the crawls now. It should be solved within 24h then.

**Comment by YiniXu9506** [comment]
Thank you so much! I will check it later.

**Comment by s-pace** [comment]
Crawl done. LMK if you notice anything weird

**Comment by YiniXu9506** [comment]
It seems still get the 404 pages and the lvl0 selector does not take effect. I will keep eyes on that and let you know if it still does not work after 5:00 PM CST. Thank you!

**Comment by YiniXu9506** [comment]
@s-pace I am sorry to let you know that the crawl haven't taken effect. Would you please check it again and reopen this issue?

**Comment by s-pace** [comment]
Yes I have checked. The crawl is really long this is why it fails (>40m)

**Comment by YiniXu9506** [comment]
Got it. Would you please let me know once the crawl succeed? Thanks.

**Comment by s-pace** [comment]
@shipow is currently running it for you

**Comment by s-pace** [comment]
@yinixu9506 done with 120k hits

**Comment by YiniXu9506** [comment]
@s-pace Thank you so much! The crawl issue has been solved.

**Comment by s-pace** [comment]
Great news 🚀
