### ISSUE TITLE
Certain v19.1 results not appearing in search results

### ISSUE THREAD

**Issue by j-low** [algolia/docsearch-configs#955]
# Do you want to request a **feature** or report a **bug**?
Bug
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= cockroachlabs

## What is the **current** behaviour?
Missing results under v19.1 (already indexed; see: https://github.com/cockroachdb/docs/issues/5132)
*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
Results for specified searches should return results

@jseldess

**Comment by s-pace** [comment]
👋🏻,

Daily crawl was failing. Issue will be solved within 24h. Please reopen if needed in 24h

**Comment by j-low** [comment]
Great, thanks for the update @s-pace

**Comment by jseldess** [comment]
@s-pace, is there any way to know when the daily crawl starting failing and how we might notice this ourselves in the future?

**Comment by s-pace** [comment]
No. We are monitoring it. If there is no update within 7 days we have an update

**Comment by jseldess** [comment]
OK, thanks, @s-pace.

**Comment by s-pace** [comment]
And this issue will never happen anymore do not worry
