### ISSUE TITLE
The page rank is disordered

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#959]
# Do you want to request a **feature** or report a **bug**?
Report a **bug**
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap.com

## What is the **current** behaviour?
The page rank of the return items are disordered.

1. Go to https://pingcap.com/docs-cn/v3.0/
2. Search "tidb operator" on the right top input
3. You will see the order of the return list does not match the page_rank I set in the start_url.
Now the order is: dev, v3.0 and v2.1. You can scroll down to see the order.

![image](https://user-images.githubusercontent.com/34967660/62550679-3af4aa80-b89d-11e9-8bdd-41d63bd5ef85.png)

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
The order of the return results should match the page_rank (v3.0, dev, v2.1) I set in docsearch-configs/pingcap.json. 

![image](https://user-images.githubusercontent.com/34967660/62551368-7643a900-b89e-11e9-8b8d-68673b1d9622.png)

#### Any quick clues?

@s-pace PTAL. Thanks

**Comment by s-pace** [comment]
The higher the ˋpage_rank` is, the higher the hit will be. You should change the value then
