### ISSUE TITLE
www.carbondesignsystem.com

### ISSUE THREAD

**Issue by alisonjoseph** [algolia/docsearch-configs#984]
Hi there! We recently pushed some major updates to our website, we're noticing general text items not show up in a search. Could you help us update our config so that the site is getting indexed properly? Thanks!

![image](https://user-images.githubusercontent.com/2753488/63710972-0a4ec380-c800-11e9-8517-48388b7c4ae1.png)

**Comment by s-pace** [comment]
Your crawl is too long. Can you render your pages only on the server side please?

It will make the crawl way much shorter

**Comment by s-pace** [comment]
@alisonjoseph it seems thats we have to emulate a browser to correctly render due to https://github.com/algolia/docsearch-configs/blob/master/configs/carbondesignsystem.json#L26:L27

Can you make sure no browser emulation are needed to render every part matching the selectors?
