### ISSUE TITLE
LivePerson category names and page names are not prioritized over page content

### ISSUE THREAD

**Issue by trosel** [algolia/docsearch-configs#987]
Regarding LivePerson documentation

* https://github.com/algolia/docsearch-configs/blob/master/configs/liveperson.json
* https://developers.liveperson.com/

## What is the **current** behaviour?

Category names and Page names are not prioritized over page content.

Search for "engagement history". The first result is the following page: https://developers.liveperson.com/mcs-toolkit-using-api-to-build-the-toolkit.html#messaging-interactions-api--engagement-history-api

![image](https://user-images.githubusercontent.com/1299322/63871354-c091e480-c989-11e9-9ac8-a993b99e68cb.png)

## What is the **expected** behaviour?

The expected first result for "engagement history" would be the following document because it is the first document in the "Engagement History API" category (and the category should be prioritized over page title and page content).

https://developers.liveperson.com/engagement-history-api-overview.html

#### What have you tried to solve it?

I believe in other Algolia search products, you can set the priority order in the admin area. But we only have the config here. Can we set the priority in the config or have someone from Algolia help us alter this?  https://github.com/algolia/docsearch-configs/blob/master/configs/liveperson.json

CC @EdenKupe

**Comment by s-pace** [comment]
👋 @trosel 

I would recommend you to use `page_rank` from `start_urls`. You can [find more details here](https://community.algolia.com/docsearch/inside-the-engine.html#ranking-records). Feel free to PR the config, we will assist you in such regards.

Cheers

**Comment by trosel** [comment]
Hey @s-pace thanks for the reply!

So I'm looking at our selectors as they currently are:

```json
"selectors": {
    "lvl0": {
      "type": "xpath",
      "selector": "//nav/a[@class='breadcrumb-item'][1]"
    },
    "lvl1": {
      "type": "xpath",
      "selector": "//nav/a[@class='breadcrumb-item'][2]"
    },
    "lvl2": {
      "type": "xpath",
      "selector": "//nav/a[@class='breadcrumb-item'][3]"
    },
    "lvl3": {
      "type": "xpath",
      "selector": "//nav/a[@class='breadcrumb-item'][4]"
    },
    "lvl4": ".post-content h3",
    "lvl5": ".post-content h4",
    "text": ".post-content p, .post-content li, .post-content td, .post-content .nx"
  },
```

And I'm looking at the engagement history API page source

view-source:https://developers.liveperson.com/engagement-history-api-overview.html
```html
<nav class="breadcrumbs breadhidden hidden-sm-down">
  <a class="breadcrumb-item" >Historical Data</a>
  <a class="breadcrumb-item" >Engagement History API</a>
  <a class="breadcrumb-item no-after" >Overview</a>
</nav>
```

## Expected Result

Searching "engagement history api" should be a lvl1 match with `<a class="breadcrumb-item" >Engagement History API</a>`

## Actual Result

Searching "engagement history api" returns the following as the first result:

view-source:https://developers.liveperson.com/mcs-toolkit-using-api-to-build-the-toolkit.html#messaging-interactions-api--engagement-history-api
`<h3 id="messaging-interactions-api--engagement-history-api">Messaging Interactions API &amp; Engagement History API</h3>`

h3 should be a lvl4 match, but it is the first match `"lvl4": ".post-content h3",`

---

Is it possible that the xpath lvl0-lvl3 just isn't written correctly? I get the impression that it just isn't working.

**Comment by s-pace** [comment]
It can be. Please PR it as you wish

**Comment by trosel** [comment]
@s-pace Is there any assistance we can get with this? After reading the docs on selectors, it **looks** correct to me. But it is not.

Is there any way to test this?

**Comment by trosel** [comment]
On http://xpather.com/ this test showed that it is correct. But I'm asking if there is something peculiar with Algolia that we are missing in order for it to work correctly.

![image](https://user-images.githubusercontent.com/1299322/63944046-d31a2580-ca3e-11e9-9575-bac53b2d72e5.png)

Any help is appreciated

**Comment by s-pace** [comment]
You can run it on your own https://community.algolia.com/docsearch/run-your-own.html

May be these elements needs js_render to be extracted

**Comment by s-pace** [comment]
Feel free to reopen if needed
