### ISSUE TITLE
Returned results are not expected

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#994]
# Do you want to request a **feature** or report a **bug**?
Report a **Bug**
### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?
I search a query, which is a title of an article. But the result does not contain this article.

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Step 1: go to https://pingcap.com/docs/v3.0
Step 2: search "Deploy TiDB Offline Using Ansible" or " Deploy TiDB Using Ansible" in the search input
Step 3: See the result does not contain this article

![image](https://user-images.githubusercontent.com/34967660/64150455-d8220f00-ce5a-11e9-92f5-107fd62d773b.png)

![image](https://user-images.githubusercontent.com/34967660/64151296-a3af5280-ce5c-11e9-930f-569c59897937.png)

## What is the **expected** behaviour?
the article "Deploy TiDB Offline Using Ansible" should be shown in the result.

#### What have you tried to solve it?
None

#### Any quick clues?
This article has been exist on website for a long time. If the cache works fine, this article should be fetched. 

### Any other feedback / questions ?
None

**Comment by YiniXu9506** [comment]
@s-pace PTAL, thanks!

**Comment by YiniXu9506** [comment]
@s-pace Why did close this issue?

**Comment by s-pace** [comment]
Solved by the new crawl.

**Comment by YiniXu9506** [comment]
It works! Thank you so much!  Will this number be update by itself or you have to do it manually?

**Comment by s-pace** [comment]
Should be updated automatically
