### ISSUE TITLE
Nothing returned

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#995]
# Do you want to request a **feature** or report a **bug**?
Report a **Bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?
No result returned

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
1. Go to https://pingcap.com/
2. Search any query, and nothing returned

![image](https://user-images.githubusercontent.com/34967660/64158118-841f2680-ce6a-11e9-923a-08564b7fa897.png)

## What is the **expected** behaviour?
There should be a return list

#### What have you tried to solve it?
None

#### Any quick clues?
Maybe Relative to: A closed issued in  1hr ago. https://github.com/algolia/docsearch-configs/issues/994

### Any other feedback / questions ?
None

**Comment by YiniXu9506** [comment]
@s-pace  PTAL, thanks!

**Comment by YiniXu9506** [comment]
Would please solve this problem so soon as possible. Users cannot use this function have a bad user experience. Thanks!

**Comment by s-pace** [comment]
Solved by a new crawl
