### ISSUE TITLE
zowe docs is not indexing properly after switch to new URL

### ISSUE THREAD

**Issue by jackjia-ibm** [algolia/docsearch-configs#998]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=zowe
Application ID: BH4D9OD16A

## What is the **current** behavior?

Currently if we visit https://docs.zowe.org/stable/ and search, for example `CLI`, it shows `No results found for query ???`. 

## What is the **expected** behavior?

Should show 5 results for popular word like `cli`.

#### What have you tried to solve it?

We recently changed start url:

```
original: "https://zowe.github.io/docs-site/(?P<version>.*?)/"
intermediate: "https://zowe.org/docs-site/(?P<version>.*?)/"
final: "https://docs.zowe.org/(?P<version>.*?)/"
```

#### Any quick clues?

It could be removing `/docs-site` from URL confused how the indexing identifies `version` from URL.

### Any other feedback / questions ?

Thanks!

**Comment by s-pace** [comment]
We crawl this:
![Uploading image.png…]()

**Comment by s-pace** [comment]
![image](https://user-images.githubusercontent.com/32097720/64233267-01db4480-cef4-11e9-8d2c-0b590b2ed91d.png)

**Comment by nannanli** [comment]
Hi @s-pace , the crawl results in the image seem correct but in our doc site, the search box does not yield any results still. See [https://docs.zowe.org/stable/](https://docs.zowe.org/stable/).Could you help take a look? Thanks!

**Comment by jackjia-ibm** [comment]
Seems it's actually caused by missing `stable` version in the definition which I missed. Thanks a lot Sylvain for looking into and fixing this.

**Comment by s-pace** [comment]
No pb :)
